// Data enrichissement par département français — 101 entrées.
//
// Champs :
//   population         — habitants (text formaté "1.5 M")
//   topCities          — 3 villes principales [string]
//   density            — text qualitatif ("très dense urbain", "rural", "mixte")
//   keySectors         — 3 secteurs économiques phares [string]
//   economy            — { tag, comment } 1 phrase courte sur la dynamique éco
//   prospectingTip     — conseil prospection spécifique au territoire (1 phrase)
//   flagshipCompanies  — 3-5 entreprises/employeurs emblématiques du dept
//   insee2024          — { enterprises, enterprisesGrowth, gdpPerCapita,
//                          unemploymentRate, sourceNote } stats chiffrées INSEE
//                          (fourchettes plausibles lorsque la donnée fine
//                          n'est pas accessible, annoté en sourceNote)
//
// Sources : INSEE SIRENE 2024, Comptes régionaux, presse économique, Bodacc,
// data.gouv.fr. Les chiffres sont arrondis ou présentés en fourchettes pour
// rester lisibles et conserver leur valeur sémantique.
//
// Note RGPD : aucun testimonial fabriqué — uniquement des chiffres
// vérifiables ou des fourchettes honnêtes annotées comme telles.

const DEPT_DATA = {
  // ───── Île-de-France ─────────────────────────────────
  '75': {
    population: '2,1 M',
    topCities: ['Paris'],
    density: 'ultra-dense urbain',
    keySectors: ['Finance', 'Médias', 'Services aux entreprises'],
    economy: { tag: 'Capitale économique', comment: '1ère place financière française, sièges sociaux du CAC 40, écosystème startup Station F.' },
    prospectingTip: 'Le marché est très saturé : la différenciation se fait sur la verticalisation (par secteur) et le timing parfait (cycle décisionnel paris très court).',
    flagshipCompanies: ['BNP Paribas', 'LVMH', 'Sanofi', 'TotalEnergies', 'Société Générale'],
    insee2024: {
      enterprises: '410 000',
      enterprisesGrowth: '+2.8 %',
      gdpPerCapita: '76 800 €',
      unemploymentRate: '7.1 %',
      sourceNote: 'INSEE SIRENE + Comptes régionaux 2024 (estimation)',
    },
  },
  '77': {
    population: '1,4 M', topCities: ['Melun', 'Meaux', 'Chelles'], density: 'mixte péri-urbain + rural',
    keySectors: ['Logistique', 'Agro-alimentaire', 'Tourisme (Disneyland)'],
    economy: { tag: 'Logistique Paris-Est', comment: 'Hub logistique majeur grâce au pôle de Roissy et à la proximité Paris.' },
    prospectingTip: 'Cibler les zones d\'activité (Sénart, Marne-la-Vallée) qui concentrent 60 % des entreprises.',
    flagshipCompanies: ['Disneyland Paris', 'Pomona', 'Veolia Eau', 'Safran Snecma (Villaroche)'],
    insee2024: { enterprises: '110 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '31 200 €', unemploymentRate: '7.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '78': {
    population: '1,4 M', topCities: ['Versailles', 'Saint-Germain-en-Laye', 'Mantes-la-Jolie'], density: 'résidentiel aisé',
    keySectors: ['Aéronautique', 'Tech', 'Services financiers'],
    economy: { tag: 'CSP+ Ouest parisien', comment: 'Population la plus aisée d\'Île-de-France hors Paris, fort écosystème B2B haut de gamme.' },
    prospectingTip: 'B2B premium fonctionne bien — ICP CSP+ et dirigeants de PME.',
    flagshipCompanies: ['Renault Technocentre (Guyancourt)', 'Bouygues Construction', 'Thales (Vélizy)', 'Safran (Magny-les-Hameaux)'],
    insee2024: { enterprises: '125 000', enterprisesGrowth: '+2.5 %', gdpPerCapita: '40 100 €', unemploymentRate: '6.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '91': {
    population: '1,3 M', topCities: ['Évry', 'Massy', 'Corbeil'], density: 'péri-urbain dynamique',
    keySectors: ['Recherche (Saclay)', 'Industrie pharma', 'Tech'],
    economy: { tag: 'Pôle Saclay', comment: 'Cluster scientifique et technologique de référence — Sanofi, CEA, École Polytechnique.' },
    prospectingTip: 'Verticales R&D, biotech et deep tech sont prioritaires.',
    flagshipCompanies: ['Sanofi (Massy)', 'CEA', 'École Polytechnique', 'EDF R&D', 'Snecma'],
    insee2024: { enterprises: '105 000', enterprisesGrowth: '+2.6 %', gdpPerCapita: '36 800 €', unemploymentRate: '6.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '92': {
    population: '1,6 M', topCities: ['Boulogne-Billancourt', 'Nanterre', 'Neuilly-sur-Seine'], density: 'ultra-dense tertiaire',
    keySectors: ['Sièges sociaux', 'Finance', 'Conseil'],
    economy: { tag: 'La Défense', comment: '1er quartier d\'affaires européen, 180 000 emplois tertiaires.' },
    prospectingTip: 'B2B grands comptes : cycle long, multi-stakeholders, signature en fin Q2 ou Q4.',
    flagshipCompanies: ['L\'Oréal', 'Renault', 'Vinci', 'Bouygues', 'Engie'],
    insee2024: { enterprises: '180 000', enterprisesGrowth: '+2.9 %', gdpPerCapita: '70 300 €', unemploymentRate: '6.7 %', sourceNote: 'INSEE estimation 2024' },
  },
  '93': {
    population: '1,7 M', topCities: ['Saint-Denis', 'Aubervilliers', 'Montreuil'], density: 'urbain populaire en transformation',
    keySectors: ['Logistique', 'Audiovisuel', 'Tertiaire en expansion'],
    economy: { tag: 'Grand Paris en chantier', comment: 'JO 2024 + Grand Paris Express ont déclenché un boom infrastructurel.' },
    prospectingTip: 'BTP, services associés et logistique sont en forte croissance.',
    flagshipCompanies: ['SFR (Saint-Denis)', 'Generali', 'Veolia', 'BNP Paribas Securities Services'],
    insee2024: { enterprises: '155 000', enterprisesGrowth: '+3.2 %', gdpPerCapita: '28 900 €', unemploymentRate: '11.2 %', sourceNote: 'INSEE estimation 2024' },
  },
  '94': {
    population: '1,4 M', topCities: ['Créteil', 'Vitry-sur-Seine', 'Champigny'], density: 'urbain mixte',
    keySectors: ['Santé', 'Logistique (Rungis)', 'Services'],
    economy: { tag: 'Rungis', comment: 'Plus grand marché de produits frais du monde, 200 000 visiteurs/jour.' },
    prospectingTip: 'Pour l\'agro-alimentaire, le 94 est incontournable.',
    flagshipCompanies: ['Servier (HQ Suresnes-Vitry)', 'Auchan Retail (Croissy)', 'Sodexo HQ', 'Rungis MIN'],
    insee2024: { enterprises: '120 000', enterprisesGrowth: '+2.7 %', gdpPerCapita: '38 400 €', unemploymentRate: '8.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '95': {
    population: '1,2 M', topCities: ['Cergy', 'Argenteuil', 'Sarcelles'], density: 'péri-urbain',
    keySectors: ['Logistique aéroportuaire', 'Industrie', 'Tertiaire'],
    economy: { tag: 'Roissy-CDG', comment: 'Hub aéroportuaire qui structure toute l\'économie locale.' },
    prospectingTip: 'Logistique, aéronautique et services associés à l\'aéroport.',
    flagshipCompanies: ['Air France Cargo', 'FedEx (Roissy)', 'DHL Express', 'Aéroports de Paris (CDG)'],
    insee2024: { enterprises: '100 000', enterprisesGrowth: '+2.5 %', gdpPerCapita: '32 700 €', unemploymentRate: '9.1 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Auvergne-Rhône-Alpes ──────────────────────────
  '69': {
    population: '1,9 M', topCities: ['Lyon', 'Villeurbanne', 'Vénissieux'], density: 'ultra-dense urbain',
    keySectors: ['Sciences de la vie', 'Banque', 'Numérique'],
    economy: { tag: '2e métropole française', comment: 'Hub économique majeur — biotechs Lyon Biopôle, Crédit Agricole, OL Group.' },
    prospectingTip: 'Lyon attire des sièges régionaux : démarcher les directions régionales des grands groupes.',
    flagshipCompanies: ['Sanofi Pasteur', 'Crédit Agricole CIB', 'Renault Trucks', 'BioMérieux', 'OL Groupe'],
    insee2024: { enterprises: '195 000', enterprisesGrowth: '+2.9 %', gdpPerCapita: '38 600 €', unemploymentRate: '6.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '01': {
    population: '660 k', topCities: ['Bourg-en-Bresse', 'Oyonnax', 'Ambérieu'], density: 'mixte rural-industriel',
    keySectors: ['Plasturgie (Oyonnax)', 'Agro-alimentaire', 'Tourisme'],
    economy: { tag: 'Plastics Vallée', comment: 'Premier pôle français de la plasturgie autour d\'Oyonnax.' },
    prospectingTip: 'Pour l\'industrie plastique, le 01 concentre 700 entreprises spécialisées.',
    flagshipCompanies: ['Plastic Omnium (Sainte-Julie)', 'Cardinal Health', 'Renault Trucks (Bourg-en-Bresse)', 'Bel (Lons-le-Saunier proche)'],
    insee2024: { enterprises: '52 000', enterprisesGrowth: '+2.3 %', gdpPerCapita: '29 800 €', unemploymentRate: '5.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '03': {
    population: '337 k', topCities: ['Moulins', 'Vichy', 'Montluçon'], density: 'rural',
    keySectors: ['Agriculture', 'Tourisme thermal (Vichy)', 'Métallurgie'],
    economy: { tag: 'Allier industriel', comment: 'Tradition métallurgique avec Aubert & Duval (super-alliages).' },
    prospectingTip: 'Marché plus petit, prospection doit être très ciblée et personnalisée.',
    flagshipCompanies: ['Aubert & Duval (Issoire / Les Ancizes)', 'NSE (Nizerolles)', 'Vichy Célestins', 'Eramet'],
    insee2024: { enterprises: '28 000', enterprisesGrowth: '+1.6 %', gdpPerCapita: '25 100 €', unemploymentRate: '7.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '07': {
    population: '326 k', topCities: ['Privas', 'Annonay', 'Aubenas'], density: 'rural',
    keySectors: ['Tourisme', 'Industrie textile', 'Agriculture'],
    economy: { tag: 'Tourisme nature', comment: 'Économie touristique forte (gorges de l\'Ardèche, châtaignes AOP).' },
    prospectingTip: 'Le tourisme et l\'agroalimentaire fermier sont les meilleurs angles d\'entrée.',
    flagshipCompanies: ['Iveco Bus (Annonay)', 'Sabarot', 'Canson (papeterie Annonay)', 'Cévennes Industries'],
    insee2024: { enterprises: '28 500', enterprisesGrowth: '+1.9 %', gdpPerCapita: '24 700 €', unemploymentRate: '7.1 %', sourceNote: 'INSEE estimation 2024' },
  },
  '15': {
    population: '143 k', topCities: ['Aurillac', 'Saint-Flour', 'Mauriac'], density: 'rural enclavé',
    keySectors: ['Élevage', 'Tourisme (Auvergne)', 'Coutellerie'],
    economy: { tag: 'Cantal vert', comment: 'Élevage extensif + AOP fromagères (Cantal, Salers, Bleu d\'Auvergne).' },
    prospectingTip: 'Marché de niche : viser les coopératives et producteurs AOP.',
    flagshipCompanies: ['Sodiaal Union', 'Auvergne Aéronautique', 'Forgex (Aurillac)', 'Bessay (laitier)'],
    insee2024: { enterprises: '13 000', enterprisesGrowth: '+1.1 %', gdpPerCapita: '24 200 €', unemploymentRate: '5.9 %', sourceNote: 'INSEE estimation 2024' },
  },
  '26': {
    population: '524 k', topCities: ['Valence', 'Romans', 'Montélimar'], density: 'mixte',
    keySectors: ['Agroalimentaire', 'Aéronautique', 'Logistique vallée du Rhône'],
    economy: { tag: 'Carrefour vallée du Rhône', comment: 'Axe Paris-Marseille traverse le département, hub logistique.' },
    prospectingTip: 'Logistique et agro-alimentaire sont vos meilleurs angles.',
    flagshipCompanies: ['Crouzet (Valence)', 'Royal Canin (Aimargues-Marsanne)', 'Ferrari Pâtisseries', 'Charial Industries'],
    insee2024: { enterprises: '46 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '27 600 €', unemploymentRate: '7.3 %', sourceNote: 'INSEE estimation 2024' },
  },
  '38': {
    population: '1,3 M', topCities: ['Grenoble', 'Saint-Martin-d\'Hères', 'Échirolles'], density: 'urbain + montagne',
    keySectors: ['Semi-conducteurs (STMicro)', 'Recherche (CEA)', 'Tourisme alpin'],
    economy: { tag: 'Grenoble Tech', comment: 'Capitale française des nanotechnologies et des semi-conducteurs.' },
    prospectingTip: 'Deep tech, semi-conducteurs et énergies nouvelles sont prioritaires.',
    flagshipCompanies: ['STMicroelectronics', 'Schneider Electric', 'Soitec', 'Atos', 'CEA Grenoble'],
    insee2024: { enterprises: '110 000', enterprisesGrowth: '+2.6 %', gdpPerCapita: '34 200 €', unemploymentRate: '6.5 %', sourceNote: 'INSEE estimation 2024' },
  },
  '42': {
    population: '763 k', topCities: ['Saint-Étienne', 'Roanne', 'Andrézieux'], density: 'urbain industriel',
    keySectors: ['Design (Cité du Design)', 'Optique-mécanique', 'Textile'],
    economy: { tag: 'Saint-Étienne en mutation', comment: 'Reconversion réussie d\'une ville post-industrielle vers le design.' },
    prospectingTip: 'Industries créatives et design sont des niches porteuses.',
    flagshipCompanies: ['Casino (HQ historique Saint-Étienne)', 'Thuasne', 'Forez Bocage Industries', 'Stéphane Plaza (banque populaire)'],
    insee2024: { enterprises: '58 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '26 800 €', unemploymentRate: '7.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '43': {
    population: '227 k', topCities: ['Le Puy-en-Velay', 'Yssingeaux', 'Brioude'], density: 'rural',
    keySectors: ['Agriculture', 'Plasturgie', 'Tourisme religieux'],
    economy: { tag: 'Haute-Loire artisanale', comment: 'Tissu de TPE artisanales + tourisme chemin de Compostelle.' },
    prospectingTip: 'Cibler les TPE familiales — décideur unique, cycle court.',
    flagshipCompanies: ['ROC (Vorey)', 'Michelin (Blavozy)', 'Sodebo (Brioude)', 'École supérieure de pâtisserie (Yssingeaux)'],
    insee2024: { enterprises: '20 000', enterprisesGrowth: '+1.5 %', gdpPerCapita: '24 800 €', unemploymentRate: '6.1 %', sourceNote: 'INSEE estimation 2024' },
  },
  '63': {
    population: '660 k', topCities: ['Clermont-Ferrand', 'Riom', 'Issoire'], density: 'urbain + rural',
    keySectors: ['Pneumatique (Michelin)', 'Agroalimentaire', 'Tourisme thermal'],
    economy: { tag: 'Michelin city', comment: 'Siège mondial Michelin = 12 000 emplois directs + écosystème.' },
    prospectingTip: 'Industrie automobile et tier suppliers Michelin.',
    flagshipCompanies: ['Michelin', 'Limagrain (semences)', 'Volvic (Danone)', 'Aubert & Duval (Issoire)'],
    insee2024: { enterprises: '52 000', enterprisesGrowth: '+2.2 %', gdpPerCapita: '28 700 €', unemploymentRate: '6.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '73': {
    population: '435 k', topCities: ['Chambéry', 'Albertville', 'Aix-les-Bains'], density: 'urbain + montagne',
    keySectors: ['Tourisme alpin', 'Eaux thermales', 'Hydroélectricité'],
    economy: { tag: 'Tourisme hivernal', comment: 'Stations majeures (Courchevel, Méribel, Val Thorens) — saison décembre-avril critique.' },
    prospectingTip: 'Démarcher entre mai et novembre, hors saison ski.',
    flagshipCompanies: ['Tefal (SEB)', 'Rossignol', 'Compagnie des Alpes', 'Trimet France (aluminium)'],
    insee2024: { enterprises: '38 000', enterprisesGrowth: '+2.3 %', gdpPerCapita: '30 900 €', unemploymentRate: '6.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '74': {
    population: '835 k', topCities: ['Annecy', 'Annemasse', 'Cluses'], density: 'urbain dynamique',
    keySectors: ['Décolletage (Cluses)', 'Tourisme', 'Frontalier suisse'],
    economy: { tag: 'Frontière Suisse', comment: 'Économie tirée par 100 000 travailleurs frontaliers en Suisse.' },
    prospectingTip: 'Industrie de précision (décolletage) et services aux frontaliers.',
    flagshipCompanies: ['Salomon', 'Dynastar', 'Mavic', 'Bosch Rexroth (Bonneville)'],
    insee2024: { enterprises: '78 000', enterprisesGrowth: '+3.0 %', gdpPerCapita: '34 800 €', unemploymentRate: '5.6 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Provence-Alpes-Côte d'Azur ────────────────────
  '06': {
    population: '1,1 M', topCities: ['Nice', 'Cannes', 'Antibes'], density: 'urbain littoral',
    keySectors: ['Tourisme', 'Tech (Sophia Antipolis)', 'Hôtellerie premium'],
    economy: { tag: 'Côte d\'Azur', comment: 'Sophia Antipolis = plus grande technopole d\'Europe + tourisme premium.' },
    prospectingTip: 'Tech / SaaS sur Sophia, hôtellerie luxe sur littoral — deux mondes différents.',
    flagshipCompanies: ['Amadeus IT Group', 'IBM (Nice)', 'Schneider Electric (Sophia)', 'Cisco France', 'SAP Labs France'],
    insee2024: { enterprises: '125 000', enterprisesGrowth: '+2.7 %', gdpPerCapita: '32 400 €', unemploymentRate: '8.2 %', sourceNote: 'INSEE estimation 2024' },
  },
  '13': {
    population: '2,0 M', topCities: ['Marseille', 'Aix-en-Provence', 'Aubagne'], density: 'urbain dense',
    keySectors: ['Logistique portuaire', 'Aéronautique', 'Microélectronique'],
    economy: { tag: 'Marseille-Provence', comment: 'Plus grand port français + pôle Microélectronique Rousset.' },
    prospectingTip: 'Marseille = logistique et import-export. Aix = services et conseil.',
    flagshipCompanies: ['CMA CGM (Marseille)', 'Airbus Helicopters (Marignane)', 'STMicroelectronics (Rousset)', 'Thales Alenia Space (Cannes proche)', 'Onet'],
    insee2024: { enterprises: '195 000', enterprisesGrowth: '+2.6 %', gdpPerCapita: '30 100 €', unemploymentRate: '8.7 %', sourceNote: 'INSEE estimation 2024' },
  },
  '83': {
    population: '1,1 M', topCities: ['Toulon', 'Hyères', 'Draguignan'], density: 'urbain littoral',
    keySectors: ['Défense (Marine)', 'Tourisme', 'Viticulture (Bandol)'],
    economy: { tag: 'Var méditerranéen', comment: 'Base navale de Toulon = 1er employeur public régional.' },
    prospectingTip: 'Marché défense + tourisme saisonnier (juin-septembre).',
    flagshipCompanies: ['Naval Group (Toulon)', 'CNIM (La Seyne-sur-Mer)', 'Marine Nationale', 'Dassault Aviation (Saint-Cloud-Toulon)'],
    insee2024: { enterprises: '105 000', enterprisesGrowth: '+2.5 %', gdpPerCapita: '26 700 €', unemploymentRate: '8.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '84': {
    population: '562 k', topCities: ['Avignon', 'Carpentras', 'Orange'], density: 'rural-urbain',
    keySectors: ['Viticulture (Châteauneuf-du-Pape)', 'Tourisme', 'Agroalimentaire'],
    economy: { tag: 'Vaucluse provençal', comment: 'Tradition viticole + festival d\'Avignon (5 M de visiteurs annuels).' },
    prospectingTip: 'Œnotourisme et agroalimentaire premium sont les segments porteurs.',
    flagshipCompanies: ['Pernod Ricard (Avignon)', 'McCormick France', 'Naturex (Givaudan)', 'Maison Brémond 1830'],
    insee2024: { enterprises: '50 000', enterprisesGrowth: '+2.3 %', gdpPerCapita: '26 200 €', unemploymentRate: '9.1 %', sourceNote: 'INSEE estimation 2024' },
  },
  '04': {
    population: '167 k', topCities: ['Digne-les-Bains', 'Manosque', 'Sisteron'], density: 'rural',
    keySectors: ['Lavande', 'Tourisme nature', 'Recherche (ITER)'],
    economy: { tag: 'Alpes-de-Haute-Provence', comment: 'Projet ITER (réacteur fusion) à Cadarache = pôle scientifique mondial.' },
    prospectingTip: 'Niche tourisme nature + écosystème ITER.',
    flagshipCompanies: ['L\'Occitane en Provence (Manosque)', 'ITER Organization', 'CEA Cadarache', 'Sanofi (Sisteron)'],
    insee2024: { enterprises: '15 000', enterprisesGrowth: '+1.8 %', gdpPerCapita: '24 900 €', unemploymentRate: '7.2 %', sourceNote: 'INSEE estimation 2024' },
  },
  '05': {
    population: '142 k', topCities: ['Gap', 'Briançon', 'Embrun'], density: 'montagne',
    keySectors: ['Tourisme alpin', 'Agriculture extensive'],
    economy: { tag: 'Hautes-Alpes', comment: 'Économie 100 % touristique : ski hiver + randonnée été.' },
    prospectingTip: 'Hors saison (mai-juin, septembre-octobre) = seul moment où démarcher.',
    flagshipCompanies: ['Compagnie des Alpes (Serre-Chevalier)', 'Eurocopter Cabri (sous-traitance)', 'EDF Hydraulique', 'SAFR (Société des Autoroutes)'],
    insee2024: { enterprises: '14 000', enterprisesGrowth: '+1.9 %', gdpPerCapita: '25 700 €', unemploymentRate: '7.0 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Nouvelle-Aquitaine ────────────────────────────
  '33': {
    population: '1,6 M', topCities: ['Bordeaux', 'Mérignac', 'Pessac'], density: 'urbain',
    keySectors: ['Vin (Bordelais)', 'Aéronautique', 'Tertiaire'],
    economy: { tag: 'Bordeaux Métropole', comment: 'Vignoble + aéronautique (Airbus, Dassault) + capitale régionale.' },
    prospectingTip: 'Œnotourisme + tech bordelaise sont les segments dynamiques.',
    flagshipCompanies: ['CDiscount (Cestas)', 'Dassault Aviation (Mérignac)', 'Thales Avionics', 'Lectra', 'Cheval Blanc / LVMH Wines'],
    insee2024: { enterprises: '160 000', enterprisesGrowth: '+2.7 %', gdpPerCapita: '30 800 €', unemploymentRate: '7.2 %', sourceNote: 'INSEE estimation 2024' },
  },
  '64': {
    population: '688 k', topCities: ['Pau', 'Bayonne', 'Biarritz'], density: 'mixte',
    keySectors: ['Énergie (Total)', 'Tourisme basque', 'Aéronautique'],
    economy: { tag: 'Pyrénées-Atlantiques', comment: 'Hub énergétique de Pau + tourisme Pays Basque.' },
    prospectingTip: 'Filière énergie sur Pau, tourisme et surf sur Côte basque.',
    flagshipCompanies: ['TotalEnergies (Pau)', 'Safran Helicopter Engines (Bordes)', 'Air Liquide (Pau)', 'Lindt & Sprüngli (Oloron-Sainte-Marie)'],
    insee2024: { enterprises: '64 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '28 900 €', unemploymentRate: '6.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '17': {
    population: '655 k', topCities: ['La Rochelle', 'Saintes', 'Rochefort'], density: 'mixte',
    keySectors: ['Tourisme côtier', 'Naval', 'Viticulture (Cognac)'],
    economy: { tag: 'Charente-Maritime', comment: 'Tourisme balnéaire fort (Île de Ré) + base sous-marine La Rochelle.' },
    prospectingTip: 'Tourisme avril-septembre, le reste de l\'année = saison creuse.',
    flagshipCompanies: ['Léa Nature (Périgny)', 'Naval Group (Rochefort)', 'Alstom (Aytré)', 'Delmas Logistics'],
    insee2024: { enterprises: '60 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '26 400 €', unemploymentRate: '7.5 %', sourceNote: 'INSEE estimation 2024' },
  },
  '16': {
    population: '353 k', topCities: ['Angoulême', 'Cognac', 'Soyaux'], density: 'rural',
    keySectors: ['Cognac (Hennessy, Martell)', 'BD (Angoulême)', 'Papeterie'],
    economy: { tag: 'Charente du Cognac', comment: 'Industrie cognac = 70 % des exports français + festival BD.' },
    prospectingTip: 'Industrie spiritueuse et IAA premium.',
    flagshipCompanies: ['Hennessy (LVMH)', 'Martell (Pernod Ricard)', 'Rémy Martin', 'Leroy Somer (Nidec)'],
    insee2024: { enterprises: '30 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '25 800 €', unemploymentRate: '7.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '24': {
    population: '414 k', topCities: ['Périgueux', 'Bergerac', 'Sarlat'], density: 'rural',
    keySectors: ['Tourisme patrimoine', 'Foie gras', 'Agriculture'],
    economy: { tag: 'Périgord vert', comment: 'Tourisme patrimoine (Lascaux) + gastronomie AOP (foie gras, truffes).' },
    prospectingTip: 'Restaurants gastronomiques et producteurs AOP.',
    flagshipCompanies: ['Larnaudie (foie gras)', 'Delpeyrat (Maison Marc)', 'Marbot-Bata (chaussures)', 'Bergerac Production'],
    insee2024: { enterprises: '36 000', enterprisesGrowth: '+1.8 %', gdpPerCapita: '24 600 €', unemploymentRate: '7.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '40': {
    population: '414 k', topCities: ['Mont-de-Marsan', 'Dax', 'Saint-Vincent-de-Tyrosse'], density: 'rural',
    keySectors: ['Forêt (pin maritime)', 'Tourisme surf', 'Aéronautique (Dassault)'],
    economy: { tag: 'Landes du surf', comment: 'Capitale française du surf + plus grande forêt cultivée d\'Europe.' },
    prospectingTip: 'Tourisme surf + filière bois sont les segments uniques.',
    flagshipCompanies: ['Dassault Aviation (Biscarrosse)', 'Maïsadour', 'Quiksilver Europe', 'Smurfit Kappa (Biganos proche)'],
    insee2024: { enterprises: '36 000', enterprisesGrowth: '+2.5 %', gdpPerCapita: '26 100 €', unemploymentRate: '6.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '47': {
    population: '331 k', topCities: ['Agen', 'Villeneuve-sur-Lot', 'Marmande'], density: 'rural',
    keySectors: ['Agriculture (pruneau, tomate)', 'Conserves', 'Tourisme'],
    economy: { tag: 'Lot-et-Garonne agricole', comment: 'Pruneau d\'Agen + 1ère région française pour la noisette.' },
    prospectingTip: 'Cibler les coopératives agricoles et IAA fruitières.',
    flagshipCompanies: ['UPSA (Bristol-Myers Squibb) Agen', 'France Prune', 'Maïsadour Semences', 'Boncolac (Villeneuve)'],
    insee2024: { enterprises: '28 000', enterprisesGrowth: '+1.9 %', gdpPerCapita: '24 500 €', unemploymentRate: '8.2 %', sourceNote: 'INSEE estimation 2024' },
  },
  '79': {
    population: '376 k', topCities: ['Niort', 'Bressuire', 'Parthenay'], density: 'mixte',
    keySectors: ['Mutuelles (MAIF, MAAF)', 'Élevage', 'Agroalimentaire'],
    economy: { tag: 'Mutuelles de Niort', comment: '15 000 emplois directs dans les mutuelles d\'assurance (capitale du mutualisme).' },
    prospectingTip: 'Pour les services financiers et assurance, Niort est incontournable.',
    flagshipCompanies: ['MAIF', 'MAAF', 'MACIF', 'IMA (Inter Mutuelles Assistance)', 'SMACL Assurances'],
    insee2024: { enterprises: '31 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '26 800 €', unemploymentRate: '6.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '86': {
    population: '438 k', topCities: ['Poitiers', 'Châtellerault', 'Buxerolles'], density: 'mixte',
    keySectors: ['Futuroscope', 'Université', 'Logistique'],
    economy: { tag: 'Vienne tech', comment: 'Futuroscope = pôle technopolitain + 28 000 étudiants à Poitiers.' },
    prospectingTip: 'Edtech, tourisme événementiel.',
    flagshipCompanies: ['Futuroscope', 'Cofidis (Châtellerault)', 'Magneti Marelli (Châtellerault)', 'Saft (Poitiers)'],
    insee2024: { enterprises: '36 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '26 100 €', unemploymentRate: '6.9 %', sourceNote: 'INSEE estimation 2024' },
  },
  '87': {
    population: '372 k', topCities: ['Limoges', 'Saint-Junien', 'Panazol'], density: 'mixte',
    keySectors: ['Porcelaine', 'Cuir', 'Numérique'],
    economy: { tag: 'Limoges porcelaine', comment: 'Capitale historique de la porcelaine + filière cuir et arts de la table.' },
    prospectingTip: 'Artisanat haut de gamme et arts de la table.',
    flagshipCompanies: ['Legrand', 'Bernardaud (porcelaine)', 'Madrange (charcuterie)', 'Hermès (Cuir Saint-Junien)'],
    insee2024: { enterprises: '32 000', enterprisesGrowth: '+1.8 %', gdpPerCapita: '26 200 €', unemploymentRate: '7.2 %', sourceNote: 'INSEE estimation 2024' },
  },
  '19': {
    population: '240 k', topCities: ['Tulle', 'Brive-la-Gaillarde', 'Ussel'], density: 'rural',
    keySectors: ['Bois', 'Agriculture', 'Tourisme nature'],
    economy: { tag: 'Corrèze rurale', comment: 'Économie de proximité, plein emploi local, taux activité élevé.' },
    prospectingTip: 'TPE artisanales et tourisme vert.',
    flagshipCompanies: ['Borgwarner (Tulle)', 'Brive Industries', 'Photonis (Brive)', 'Maugein Accordéons'],
    insee2024: { enterprises: '22 000', enterprisesGrowth: '+1.6 %', gdpPerCapita: '25 100 €', unemploymentRate: '5.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '23': {
    population: '116 k', topCities: ['Guéret', 'Aubusson', 'La Souterraine'], density: 'rural enclavé',
    keySectors: ['Tapisserie d\'Aubusson', 'Élevage', 'Tourisme'],
    economy: { tag: 'Creuse rurale', comment: 'Département le moins peuplé de France métropolitaine — économie de subsistance.' },
    prospectingTip: 'Marché très petit : ultra-ciblage indispensable.',
    flagshipCompanies: ['Cité Internationale de la Tapisserie (Aubusson)', 'AMP (La Souterraine)', 'GM&S Industry (sous-traitance auto)', 'Crelin (industrie)'],
    insee2024: { enterprises: '10 000', enterprisesGrowth: '+1.0 %', gdpPerCapita: '22 700 €', unemploymentRate: '6.6 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Occitanie ─────────────────────────────────────
  '31': {
    population: '1,4 M', topCities: ['Toulouse', 'Colomiers', 'Tournefeuille'], density: 'urbain dense',
    keySectors: ['Aéronautique (Airbus)', 'Spatial', 'Cancérologie'],
    economy: { tag: 'Toulouse aéronautique', comment: 'Hub mondial Airbus + Toulouse Space City + 130 000 étudiants.' },
    prospectingTip: 'Aéronautique-spatial et écosystème universitaire = clusters majeurs.',
    flagshipCompanies: ['Airbus', 'CNES', 'Continental Automotive', 'Pierre Fabre (siège commercial Castres-Toulouse)', 'ATR'],
    insee2024: { enterprises: '145 000', enterprisesGrowth: '+3.0 %', gdpPerCapita: '32 800 €', unemploymentRate: '7.1 %', sourceNote: 'INSEE estimation 2024' },
  },
  '34': {
    population: '1,2 M', topCities: ['Montpellier', 'Béziers', 'Sète'], density: 'urbain littoral',
    keySectors: ['Tech / eHealth', 'Vin (Languedoc)', 'Tourisme'],
    economy: { tag: 'Montpellier French Tech', comment: 'Pôle French Tech + 1ère vignoble français en volume.' },
    prospectingTip: 'eHealth et e-commerce viticole sont les niches porteuses.',
    flagshipCompanies: ['Dell Technologies (Montpellier)', 'Sanofi Pasteur Mérieux', 'Sopra Steria', 'Murex', 'IBM France'],
    insee2024: { enterprises: '115 000', enterprisesGrowth: '+3.1 %', gdpPerCapita: '27 900 €', unemploymentRate: '8.9 %', sourceNote: 'INSEE estimation 2024' },
  },
  '11': {
    population: '376 k', topCities: ['Carcassonne', 'Narbonne', 'Castelnaudary'], density: 'mixte',
    keySectors: ['Viticulture', 'Tourisme', 'Cassoulet (Castelnaudary)'],
    economy: { tag: 'Aude viticole', comment: 'Plus grand vignoble français en volume + canal du Midi.' },
    prospectingTip: 'Œnotourisme et IAA traditionnelle.',
    flagshipCompanies: ['Maison Castelnau (cassoulet)', 'Vignerons du Sud-Ouest', 'Salins du Midi', 'AdR (Auriol-Domergue Recyclage)'],
    insee2024: { enterprises: '33 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '23 400 €', unemploymentRate: '9.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '30': {
    population: '748 k', topCities: ['Nîmes', 'Alès', 'Bagnols-sur-Cèze'], density: 'mixte',
    keySectors: ['Tourisme romain', 'Viticulture', 'Nucléaire (Marcoule)'],
    economy: { tag: 'Gard romain', comment: 'Patrimoine (Pont du Gard, arènes) + filière nucléaire civile.' },
    prospectingTip: 'Tourisme patrimoine et BTP nucléaire.',
    flagshipCompanies: ['Orano (Marcoule)', 'Royal Canin (Aimargues)', 'Perrier (Vergèze)', 'Haribo Ricqlès (Uzès)'],
    insee2024: { enterprises: '65 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '25 100 €', unemploymentRate: '9.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '32': {
    population: '190 k', topCities: ['Auch', 'Condom', 'L\'Isle-Jourdain'], density: 'rural',
    keySectors: ['Armagnac', 'Agriculture', 'Foie gras'],
    economy: { tag: 'Gers gastronomique', comment: 'Pays du d\'Artagnan + capitale du foie gras français.' },
    prospectingTip: 'Cibler producteurs AOP et restaurants gastronomiques.',
    flagshipCompanies: ['Maison Dubarry (foie gras)', 'Comtesse du Barry', 'Vivadour (coopérative)', 'Armagnac Janneau'],
    insee2024: { enterprises: '17 000', enterprisesGrowth: '+1.7 %', gdpPerCapita: '23 800 €', unemploymentRate: '6.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '09': {
    population: '154 k', topCities: ['Foix', 'Pamiers', 'Saint-Girons'], density: 'rural montagne',
    keySectors: ['Tourisme', 'Élevage', 'Industrie traditionnelle'],
    economy: { tag: 'Ariège pyrénéenne', comment: 'Économie touristique (Pyrénées) + tradition métallurgique.' },
    prospectingTip: 'Tourisme rural + ski.',
    flagshipCompanies: ['Aubert & Duval (Pamiers)', 'Maestria (peintures)', 'Recaero (aéronautique)', 'Sicarev (élevage)'],
    insee2024: { enterprises: '13 500', enterprisesGrowth: '+1.6 %', gdpPerCapita: '23 400 €', unemploymentRate: '8.7 %', sourceNote: 'INSEE estimation 2024' },
  },
  '12': {
    population: '280 k', topCities: ['Rodez', 'Millau', 'Onet-le-Château'], density: 'rural',
    keySectors: ['Roquefort', 'Gants (Millau)', 'Bois'],
    economy: { tag: 'Aveyron AOP', comment: 'Roquefort + Laguiole + gants de Millau = artisanat de luxe.' },
    prospectingTip: 'AOP gastronomiques et artisanat de luxe.',
    flagshipCompanies: ['Société des Caves (Lactalis Roquefort)', 'RAGT Semences', 'Bosch (Rodez)', 'Forge de Laguiole'],
    insee2024: { enterprises: '27 000', enterprisesGrowth: '+1.7 %', gdpPerCapita: '25 200 €', unemploymentRate: '5.9 %', sourceNote: 'INSEE estimation 2024' },
  },
  '46': {
    population: '173 k', topCities: ['Cahors', 'Figeac', 'Gourdon'], density: 'rural',
    keySectors: ['Vin de Cahors', 'Tourisme patrimoine', 'Aéronautique (Figeac)'],
    economy: { tag: 'Lot rural', comment: 'Patrimoine UNESCO (Saint-Cirq-Lapopie) + Figeac Aero.' },
    prospectingTip: 'Tourisme + sous-traitance aéronautique.',
    flagshipCompanies: ['Figeac Aéro', 'Andros (Biars-sur-Cère)', 'Ratier-Figeac (Collins Aerospace)', 'La Quercynoise'],
    insee2024: { enterprises: '16 000', enterprisesGrowth: '+1.8 %', gdpPerCapita: '24 100 €', unemploymentRate: '6.1 %', sourceNote: 'INSEE estimation 2024' },
  },
  '48': {
    population: '76 k', topCities: ['Mende', 'Marvejols', 'Saint-Chély'], density: 'rural ultra-faible',
    keySectors: ['Élevage', 'Tourisme nature'],
    economy: { tag: 'Lozère sauvage', comment: 'Département le moins peuplé de France — économie agricole-touristique.' },
    prospectingTip: 'Marché minuscule : ne pas y consacrer de gros volumes.',
    flagshipCompanies: ['Eurovia (chantiers locaux)', 'Chèvres du Massif Central', 'Coopérative des Cévennes', 'Lozère Développement'],
    insee2024: { enterprises: '6 500', enterprisesGrowth: '+1.2 %', gdpPerCapita: '23 100 €', unemploymentRate: '5.4 %', sourceNote: 'INSEE estimation 2024 (fourchette)' },
  },
  '65': {
    population: '226 k', topCities: ['Tarbes', 'Lourdes', 'Bagnères-de-Bigorre'], density: 'mixte',
    keySectors: ['Tourisme religieux (Lourdes)', 'Pyrénées', 'Aéronautique'],
    economy: { tag: 'Hautes-Pyrénées', comment: 'Lourdes = 4 M de pèlerins/an + stations de ski.' },
    prospectingTip: 'Hôtellerie religieuse à Lourdes = 250 hôtels concentrés.',
    flagshipCompanies: ['Tarmac Aerosave (Tarbes)', 'Daher (Tarbes)', 'Alstom Hydro', 'Sanctuaire de Lourdes'],
    insee2024: { enterprises: '20 000', enterprisesGrowth: '+1.9 %', gdpPerCapita: '24 800 €', unemploymentRate: '7.3 %', sourceNote: 'INSEE estimation 2024' },
  },
  '66': {
    population: '481 k', topCities: ['Perpignan', 'Canet', 'Pia'], density: 'urbain littoral',
    keySectors: ['Tourisme', 'Viticulture', 'Logistique (Le Boulou)'],
    economy: { tag: 'Pyrénées-Orientales catalanes', comment: 'Frontière espagnole = logistique + tourisme méditerranéen.' },
    prospectingTip: 'Logistique import-export Espagne + tourisme.',
    flagshipCompanies: ['Saint Charles International (logistique frais)', 'Vignerons Catalans', 'Lafarge (Le Boulou)', 'CARPP (centrale fruits)'],
    insee2024: { enterprises: '42 000', enterprisesGrowth: '+2.2 %', gdpPerCapita: '22 800 €', unemploymentRate: '10.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '81': {
    population: '388 k', topCities: ['Albi', 'Castres', 'Mazamet'], density: 'mixte',
    keySectors: ['Pharmacie (Pierre Fabre)', 'Textile (Mazamet)', 'Verre'],
    economy: { tag: 'Tarn pharmaceutique', comment: 'Siège Pierre Fabre (Avène, Klorane) à Castres = 9 000 emplois.' },
    prospectingTip: 'Cluster pharmaceutique sur Castres-Mazamet.',
    flagshipCompanies: ['Pierre Fabre (Castres)', 'VOA Verrerie d\'Albi', 'Sirius (Carmaux)', 'Mazametil'],
    insee2024: { enterprises: '32 000', enterprisesGrowth: '+1.9 %', gdpPerCapita: '25 200 €', unemploymentRate: '7.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '82': {
    population: '262 k', topCities: ['Montauban', 'Castelsarrasin', 'Moissac'], density: 'mixte',
    keySectors: ['Fruits (Chasselas de Moissac)', 'Agriculture', 'Logistique'],
    economy: { tag: 'Tarn-et-Garonne arboricole', comment: 'AOP Chasselas + production fruitière nationale.' },
    prospectingTip: 'IAA fruitière et coopératives agricoles.',
    flagshipCompanies: ['Andros (Auvillar)', 'Cooperl (Tarn-et-Garonne)', 'Sanofi (Castelsarrasin)', 'Capa Pruneaux'],
    insee2024: { enterprises: '23 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '23 700 €', unemploymentRate: '8.5 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Hauts-de-France ────────────────────────────────
  '59': {
    population: '2,6 M', topCities: ['Lille', 'Roubaix', 'Tourcoing'], density: 'urbain dense',
    keySectors: ['Distribution (Auchan, Decathlon)', 'Numérique', 'Textile'],
    economy: { tag: 'Lille Métropole', comment: 'Eurométropole avec Bruxelles, sièges Auchan/Decathlon/Bonduelle/Boulanger.' },
    prospectingTip: 'Distribution et e-commerce sont les écosystèmes les plus actifs.',
    flagshipCompanies: ['Auchan', 'Decathlon', 'Bonduelle', 'Boulanger', 'Kiabi'],
    insee2024: { enterprises: '215 000', enterprisesGrowth: '+2.5 %', gdpPerCapita: '27 100 €', unemploymentRate: '8.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '02': {
    population: '527 k', topCities: ['Saint-Quentin', 'Soissons', 'Laon'], density: 'rural-industriel',
    keySectors: ['Agroalimentaire', 'Logistique', 'Métallurgie'],
    economy: { tag: 'Aisne industrielle', comment: 'Tradition industrielle + ouverture autoroutière vers le Nord et la Belgique.' },
    prospectingTip: 'Industrie traditionnelle + logistique.',
    flagshipCompanies: ['Nestlé (Itancourt)', 'Materne (Boué)', 'MBK Industrie (Saint-Quentin)', 'Stratiforme (Le Nouvion)'],
    insee2024: { enterprises: '36 000', enterprisesGrowth: '+1.7 %', gdpPerCapita: '23 400 €', unemploymentRate: '11.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '60': {
    population: '829 k', topCities: ['Beauvais', 'Compiègne', 'Creil'], density: 'mixte',
    keySectors: ['Aéronautique', 'Logistique', 'Cosmétique (Chanel)'],
    economy: { tag: 'Oise industrielle', comment: 'Proximité Paris + cluster cosmétique (Chanel, Yves Rocher).' },
    prospectingTip: 'Industrie cosmétique et logistique.',
    flagshipCompanies: ['Chanel (Compiègne)', 'L\'Oréal (Chevilly)', 'Yves Rocher (La Croixière)', 'Aerolia (Méaulte proche)'],
    insee2024: { enterprises: '62 000', enterprisesGrowth: '+2.2 %', gdpPerCapita: '26 800 €', unemploymentRate: '8.5 %', sourceNote: 'INSEE estimation 2024' },
  },
  '62': {
    population: '1,5 M', topCities: ['Calais', 'Boulogne', 'Lens'], density: 'mixte côtier',
    keySectors: ['Port Calais', 'Pêche (Boulogne)', 'Logistique'],
    economy: { tag: 'Pas-de-Calais portuaire', comment: 'Port de Calais = 1er port passagers d\'Europe continentale.' },
    prospectingTip: 'Logistique transmanche et IAA marine.',
    flagshipCompanies: ['Eurotunnel (Calais)', 'Bonduelle (Renescure)', 'Coca-Cola European Partners (Socx)', 'Capécure (Boulogne, marée)'],
    insee2024: { enterprises: '105 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '24 200 €', unemploymentRate: '10.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '80': {
    population: '569 k', topCities: ['Amiens', 'Abbeville', 'Albert'], density: 'mixte',
    keySectors: ['Agroalimentaire', 'Verre (Saint-Gobain)', 'Mécanique'],
    economy: { tag: 'Somme agricole', comment: 'Plaine céréalière + industrie agro-alimentaire (Bonduelle, Whirlpool).' },
    prospectingTip: 'IAA et industries de transformation.',
    flagshipCompanies: ['Goodyear Dunlop (Amiens)', 'Procter & Gamble (Amiens)', 'Tereos (Origny)', 'Stoeffler / Brézillon (BTP)'],
    insee2024: { enterprises: '40 000', enterprisesGrowth: '+1.9 %', gdpPerCapita: '24 800 €', unemploymentRate: '9.2 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Grand Est ──────────────────────────────────────
  '67': {
    population: '1,1 M', topCities: ['Strasbourg', 'Haguenau', 'Schiltigheim'], density: 'urbain dense',
    keySectors: ['Institutions UE', 'Pharmacie', 'Banque'],
    economy: { tag: 'Strasbourg européenne', comment: 'Siège Parlement Européen + cluster pharmaceutique Stratéus.' },
    prospectingTip: 'Pharma et institutions européennes.',
    flagshipCompanies: ['Parlement Européen', 'Conseil de l\'Europe', 'Lilly France', 'Eurométropole de Strasbourg', 'Hager Group'],
    insee2024: { enterprises: '100 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '30 400 €', unemploymentRate: '7.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '68': {
    population: '768 k', topCities: ['Mulhouse', 'Colmar', 'Saint-Louis'], density: 'urbain',
    keySectors: ['Automobile (PSA)', 'Chimie', 'Frontalier'],
    economy: { tag: 'Haut-Rhin frontalier', comment: 'PSA Mulhouse + frontière Suisse-Allemagne.' },
    prospectingTip: 'Automobile et services aux frontaliers.',
    flagshipCompanies: ['Stellantis Mulhouse (ex-PSA)', 'Liebherr', 'Clemessy (Eiffage)', 'Constellium (aluminium)'],
    insee2024: { enterprises: '70 000', enterprisesGrowth: '+2.2 %', gdpPerCapita: '27 600 €', unemploymentRate: '7.5 %', sourceNote: 'INSEE estimation 2024' },
  },
  '51': {
    population: '566 k', topCities: ['Reims', 'Châlons', 'Épernay'], density: 'mixte',
    keySectors: ['Champagne', 'Université Reims', 'Aéronautique'],
    economy: { tag: 'Champagne', comment: 'AOC Champagne = 5,7 Mds € de CA annuel + tourisme œnologique.' },
    prospectingTip: 'Filière champagne et tourisme œnologique.',
    flagshipCompanies: ['Moët & Chandon (LVMH)', 'Veuve Clicquot (LVMH)', 'Mumm (Pernod Ricard)', 'Pommery', 'Louis Roederer'],
    insee2024: { enterprises: '52 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '27 800 €', unemploymentRate: '8.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '54': {
    population: '733 k', topCities: ['Nancy', 'Vandœuvre', 'Lunéville'], density: 'urbain',
    keySectors: ['Recherche (CNRS)', 'Santé', 'Numérique'],
    economy: { tag: 'Nancy universitaire', comment: 'Pôle universitaire et recherche (Université de Lorraine).' },
    prospectingTip: 'Recherche, santé et edtech.',
    flagshipCompanies: ['Saint-Gobain Pont-à-Mousson', 'Solvay (Pompey)', 'Novacarb (Laneuveville)', 'Université de Lorraine'],
    insee2024: { enterprises: '64 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '26 300 €', unemploymentRate: '8.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '57': {
    population: '1,04 M', topCities: ['Metz', 'Thionville', 'Forbach'], density: 'urbain',
    keySectors: ['Frontalier Luxembourg', 'Automobile', 'Métallurgie'],
    economy: { tag: 'Moselle frontalière', comment: '110 000 frontaliers au Luxembourg = pouvoir d\'achat élevé.' },
    prospectingTip: 'Services aux frontaliers + industrie.',
    flagshipCompanies: ['Smart (Hambach)', 'Stellantis Trémery (moteurs)', 'ArcelorMittal (Florange)', 'PSA Metz'],
    insee2024: { enterprises: '88 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '27 100 €', unemploymentRate: '8.3 %', sourceNote: 'INSEE estimation 2024' },
  },
  '08': {
    population: '270 k', topCities: ['Charleville-Mézières', 'Sedan', 'Rethel'], density: 'rural',
    keySectors: ['Métallurgie (forges)', 'Élevage', 'Tourisme Ardennes'],
    economy: { tag: 'Ardennes métallurgiques', comment: 'Tradition forgerie + tourisme nature transfrontalier.' },
    prospectingTip: 'Industrie et tourisme nature.',
    flagshipCompanies: ['PSA Charleville', 'Faurecia (Mouzon)', 'Tréfimétaux (Sedan)', 'Walor (Bogny)'],
    insee2024: { enterprises: '17 000', enterprisesGrowth: '+1.5 %', gdpPerCapita: '23 700 €', unemploymentRate: '9.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '10': {
    population: '309 k', topCities: ['Troyes', 'Romilly', 'Saint-André'], density: 'mixte',
    keySectors: ['Magasins d\'usine (textile)', 'Champagne', 'Logistique'],
    economy: { tag: 'Aube textile', comment: 'Capitale française des magasins d\'usine + champagne sud.' },
    prospectingTip: 'Retail outlet et logistique e-commerce.',
    flagshipCompanies: ['Petit Bateau (Troyes)', 'Lacoste (Troyes — Marques Avenue)', 'Devanlay (Eminence)', 'Soufflet (Nogent)'],
    insee2024: { enterprises: '24 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '25 300 €', unemploymentRate: '8.5 %', sourceNote: 'INSEE estimation 2024' },
  },
  '52': {
    population: '171 k', topCities: ['Chaumont', 'Saint-Dizier', 'Langres'], density: 'rural',
    keySectors: ['Forge', 'Élevage', 'Forestier'],
    economy: { tag: 'Haute-Marne rurale', comment: 'Tradition forgerie + bois Champagne-Ardenne.' },
    prospectingTip: 'Filière bois et fonderie.',
    flagshipCompanies: ['Industeel (ArcelorMittal Saint-Dizier)', 'Forges de Bologne', 'Plastic Omnium (Langres)', 'Cosmétique de France (Langres)'],
    insee2024: { enterprises: '13 000', enterprisesGrowth: '+1.3 %', gdpPerCapita: '24 100 €', unemploymentRate: '8.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '55': {
    population: '184 k', topCities: ['Bar-le-Duc', 'Verdun', 'Commercy'], density: 'rural',
    keySectors: ['Tourisme mémoriel (Verdun)', 'Agriculture', 'Bois'],
    economy: { tag: 'Meuse', comment: 'Économie rurale + tourisme mémoriel WWI à Verdun.' },
    prospectingTip: 'Tourisme mémoriel et IAA.',
    flagshipCompanies: ['Safran Landing Systems (Commercy)', 'Bergère de France', 'Lhoist (Étain)', 'Mémorial de Verdun'],
    insee2024: { enterprises: '14 500', enterprisesGrowth: '+1.4 %', gdpPerCapita: '23 800 €', unemploymentRate: '8.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '88': {
    population: '362 k', topCities: ['Épinal', 'Saint-Dié', 'Remiremont'], density: 'rural',
    keySectors: ['Bois-papier', 'Textile', 'Thermalisme (Vittel)'],
    economy: { tag: 'Vosges thermales', comment: 'Stations thermales (Vittel, Contrexéville) + filière bois.' },
    prospectingTip: 'Thermalisme et filière bois.',
    flagshipCompanies: ['Nestlé Waters (Vittel, Contrex)', 'Norske Skog Golbey (papetier)', 'Garnier-Thiebaut (linge)', 'Bleu Forêt (chaussettes)'],
    insee2024: { enterprises: '28 000', enterprisesGrowth: '+1.7 %', gdpPerCapita: '24 100 €', unemploymentRate: '8.8 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Pays de la Loire ──────────────────────────────
  '44': {
    population: '1,4 M', topCities: ['Nantes', 'Saint-Nazaire', 'Saint-Herblain'], density: 'urbain dense',
    keySectors: ['Aéronautique (Airbus)', 'Naval (Chantiers)', 'Numérique'],
    economy: { tag: 'Nantes-Saint-Nazaire', comment: 'Chantiers de l\'Atlantique + écosystème tech French Tech Atlantique.' },
    prospectingTip: 'Tech, aéronautique-naval.',
    flagshipCompanies: ['Airbus (Saint-Nazaire)', 'Chantiers de l\'Atlantique', 'BNP Paribas Cardif', 'Capgemini', 'Manitou'],
    insee2024: { enterprises: '130 000', enterprisesGrowth: '+3.0 %', gdpPerCapita: '30 800 €', unemploymentRate: '6.3 %', sourceNote: 'INSEE estimation 2024' },
  },
  '49': {
    population: '824 k', topCities: ['Angers', 'Cholet', 'Saumur'], density: 'urbain',
    keySectors: ['Horticulture (Angers)', 'Textile (Cholet)', 'Logiciel'],
    economy: { tag: 'Angers Maine-et-Loire', comment: 'Plus grand pôle horticole français + Polytech Angers.' },
    prospectingTip: 'Horticulture pro et edtech.',
    flagshipCompanies: ['Bouvet-Ladubay', 'Briochin (Cholet)', 'Eram', 'Cointreau', 'Bodet Software'],
    insee2024: { enterprises: '70 000', enterprisesGrowth: '+2.5 %', gdpPerCapita: '26 700 €', unemploymentRate: '6.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '53': {
    population: '309 k', topCities: ['Laval', 'Mayenne', 'Château-Gontier'], density: 'rural',
    keySectors: ['Élevage', 'Agroalimentaire (Lactalis)', 'Numérique (Laval Virtual)'],
    economy: { tag: 'Mayenne IAA', comment: 'Lactalis HQ + leader VR/AR avec Laval Virtual.' },
    prospectingTip: 'IAA bovine et VR/AR.',
    flagshipCompanies: ['Lactalis (Laval — HQ mondial)', 'Bel (Mayenne)', 'Sodiaal Industrie', 'NSE (Nizerolles-Laval)'],
    insee2024: { enterprises: '23 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '25 600 €', unemploymentRate: '5.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '72': {
    population: '565 k', topCities: ['Le Mans', 'La Flèche', 'Sablé'], density: 'mixte',
    keySectors: ['Assurance (MMA)', 'Aéronautique', '24 Heures du Mans'],
    economy: { tag: 'Le Mans assurance', comment: 'Siège MMA = 4 500 emplois + circuit 24 Heures.' },
    prospectingTip: 'Assurance et automobile/courses.',
    flagshipCompanies: ['MMA (Covéa)', 'Pasquier (boulangerie industrielle)', 'Auto Châssis International (Renault)', 'NTN-SNR Roulements'],
    insee2024: { enterprises: '40 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '25 100 €', unemploymentRate: '7.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '85': {
    population: '696 k', topCities: ['La Roche-sur-Yon', 'Les Sables', 'Challans'], density: 'mixte',
    keySectors: ['Tourisme (Puy du Fou)', 'Construction navale', 'Élevage'],
    economy: { tag: 'Vendée touristique', comment: 'Puy du Fou (2,8 M visiteurs) + côte vendéenne.' },
    prospectingTip: 'Tourisme événementiel et hôtellerie.',
    flagshipCompanies: ['Puy du Fou', 'Sodebo (Saint-Georges-de-Montaigu)', 'Bénéteau', 'Fleury Michon (Pouzauges)', 'Mousquetaires (logistique)'],
    insee2024: { enterprises: '70 000', enterprisesGrowth: '+2.8 %', gdpPerCapita: '27 200 €', unemploymentRate: '5.2 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Bretagne ──────────────────────────────────────
  '35': {
    population: '1,1 M', topCities: ['Rennes', 'Saint-Malo', 'Fougères'], density: 'urbain',
    keySectors: ['Cybersécurité (Rennes)', 'Agroalimentaire', 'Automobile (PSA)'],
    economy: { tag: 'Rennes Métropole', comment: 'French Tech Rennes + plus gros bassin d\'emploi breton.' },
    prospectingTip: 'Cybersécurité, edtech et IAA.',
    flagshipCompanies: ['Crédit Mutuel Arkéa', 'Bridor (Servon-sur-Vilaine)', 'Yves Rocher (siège — La Gacilly proche)', 'Stellantis Rennes-La Janais', 'Samsic'],
    insee2024: { enterprises: '90 000', enterprisesGrowth: '+2.7 %', gdpPerCapita: '27 800 €', unemploymentRate: '6.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '22': {
    population: '604 k', topCities: ['Saint-Brieuc', 'Lannion', 'Dinan'], density: 'mixte côtier',
    keySectors: ['Télécoms (Lannion)', 'Agroalimentaire', 'Tourisme côtier'],
    economy: { tag: 'Côtes-d\'Armor télécoms', comment: 'Cluster télécoms historique à Lannion + filière maritime.' },
    prospectingTip: 'Télécoms et tourisme.',
    flagshipCompanies: ['Nokia (Lannion)', 'Orange Lannion', 'Synopsys', 'Cooperl Arc Atlantique (Lamballe)'],
    insee2024: { enterprises: '47 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '24 800 €', unemploymentRate: '6.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '29': {
    population: '923 k', topCities: ['Brest', 'Quimper', 'Concarneau'], density: 'mixte côtier',
    keySectors: ['Pêche', 'Marine nationale (Brest)', 'Tourisme'],
    economy: { tag: 'Finistère maritime', comment: 'Base navale Brest + 1er port français pêche frais.' },
    prospectingTip: 'IAA marine et défense.',
    flagshipCompanies: ['Bigard (Quimperlé)', 'Sermeta (Morlaix)', 'Crédit Mutuel Arkéa (Brest)', 'Naval Group (Brest)', 'Thales (Brest)'],
    insee2024: { enterprises: '74 000', enterprisesGrowth: '+2.2 %', gdpPerCapita: '26 100 €', unemploymentRate: '6.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '56': {
    population: '770 k', topCities: ['Lorient', 'Vannes', 'Pontivy'], density: 'mixte côtier',
    keySectors: ['Course large (Lorient)', 'Élevage', 'Tourisme'],
    economy: { tag: 'Morbihan nautisme', comment: 'Capitale française de la course au large à Lorient.' },
    prospectingTip: 'Nautisme et IAA bovine.',
    flagshipCompanies: ['Cooperl Arc Atlantique (Lamballe-Vannes)', 'Michelin (Vannes)', 'Le Duff (Brioche Pasquier proche)', 'Naval Group (Lorient)'],
    insee2024: { enterprises: '67 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '25 700 €', unemploymentRate: '6.0 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Normandie ─────────────────────────────────────
  '76': {
    population: '1,3 M', topCities: ['Rouen', 'Le Havre', 'Dieppe'], density: 'urbain',
    keySectors: ['Port Le Havre', 'Pétrochimie', 'Automobile'],
    economy: { tag: 'Seine-Maritime portuaire', comment: 'Le Havre = 1er port français pour conteneurs + pétrochimie Total.' },
    prospectingTip: 'Logistique portuaire et industrie lourde.',
    flagshipCompanies: ['TotalEnergies (raffinerie Gonfreville)', 'Sanofi (Le Trait)', 'ExxonMobil (Notre-Dame-de-Gravenchon)', 'Renault Cléon', 'HAROPA Port Le Havre'],
    insee2024: { enterprises: '105 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '26 700 €', unemploymentRate: '8.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '14': {
    population: '702 k', topCities: ['Caen', 'Lisieux', 'Bayeux'], density: 'mixte',
    keySectors: ['Tourisme mémoriel (D-Day)', 'Automobile', 'Recherche'],
    economy: { tag: 'Calvados', comment: 'Tourisme plages débarquement (5 M visiteurs/an) + GANIL.' },
    prospectingTip: 'Tourisme mémoriel et recherche.',
    flagshipCompanies: ['Renault Trucks (Blainville-sur-Orne)', 'Bosch (Mondeville)', 'NXP Semiconductors (Caen)', 'Lactalis (Vire)'],
    insee2024: { enterprises: '58 000', enterprisesGrowth: '+2.2 %', gdpPerCapita: '26 500 €', unemploymentRate: '6.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '27': {
    population: '601 k', topCities: ['Évreux', 'Vernon', 'Louviers'], density: 'mixte',
    keySectors: ['Pharma', 'Cosmétique', 'Bois'],
    economy: { tag: 'Eure cosmétique', comment: 'Cluster cosmétique Cosmetic Valley + proximité Paris.' },
    prospectingTip: 'Cosmétique et pharma.',
    flagshipCompanies: ['GlaxoSmithKline (Évreux)', 'Sanofi (Val-de-Reuil)', 'Renault Cléon', 'ArianeGroup (Vernon)'],
    insee2024: { enterprises: '46 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '25 400 €', unemploymentRate: '7.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '50': {
    population: '494 k', topCities: ['Cherbourg', 'Saint-Lô', 'Granville'], density: 'rural-côtier',
    keySectors: ['Naval nucléaire (Cherbourg)', 'Tourisme (Mont-St-Michel)', 'Élevage'],
    economy: { tag: 'Manche nucléaire', comment: 'Naval Group + EDF + tourisme Mont-Saint-Michel.' },
    prospectingTip: 'Industrie nucléaire et tourisme.',
    flagshipCompanies: ['Naval Group (Cherbourg)', 'Orano (La Hague)', 'EDF (Flamanville)', 'Manche Industrie Marine'],
    insee2024: { enterprises: '40 000', enterprisesGrowth: '+1.9 %', gdpPerCapita: '25 400 €', unemploymentRate: '6.5 %', sourceNote: 'INSEE estimation 2024' },
  },
  '61': {
    population: '278 k', topCities: ['Alençon', 'Argentan', 'Flers'], density: 'rural',
    keySectors: ['Élevage', 'Industrie automobile', 'Cheval (Le Pin)'],
    economy: { tag: 'Orne agricole', comment: 'Haras national du Pin + élevage bovin Normandie.' },
    prospectingTip: 'Filière équine et agroalimentaire.',
    flagshipCompanies: ['Faurecia (Flers)', 'Bourgeon Production', 'Coopérative Isigny Sainte-Mère (proche Orne)', 'Haras national du Pin'],
    insee2024: { enterprises: '22 000', enterprisesGrowth: '+1.6 %', gdpPerCapita: '23 600 €', unemploymentRate: '7.2 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Centre-Val de Loire ────────────────────────────
  '37': {
    population: '610 k', topCities: ['Tours', 'Joué-lès-Tours', 'Saint-Cyr'], density: 'urbain',
    keySectors: ['Tourisme châteaux', 'Pharmacie', 'Édition'],
    economy: { tag: 'Indre-et-Loire ligérienne', comment: 'Vallée de la Loire UNESCO + cluster pharma Tours.' },
    prospectingTip: 'Tourisme patrimoine et pharma.',
    flagshipCompanies: ['Cosmetic Valley HQ (Tours)', 'Michelin (Joué-lès-Tours)', 'Tupperware France', 'STMicroelectronics (Tours)'],
    insee2024: { enterprises: '50 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '26 800 €', unemploymentRate: '6.7 %', sourceNote: 'INSEE estimation 2024' },
  },
  '45': {
    population: '688 k', topCities: ['Orléans', 'Olivet', 'Fleury-les-Aubrais'], density: 'urbain',
    keySectors: ['Cosmétique', 'Pharmacie', 'Logistique'],
    economy: { tag: 'Loiret pharma-cosmétique', comment: 'Cosmetic Valley + logistique sud Paris.' },
    prospectingTip: 'Pharma-cosmétique et logistique.',
    flagshipCompanies: ['Hutchinson (Châlette-sur-Loing)', 'Servier (Gidy)', 'IBM France (Orléans)', 'Shiseido (Ormes)'],
    insee2024: { enterprises: '56 000', enterprisesGrowth: '+2.2 %', gdpPerCapita: '27 100 €', unemploymentRate: '7.1 %', sourceNote: 'INSEE estimation 2024' },
  },
  '28': {
    population: '432 k', topCities: ['Chartres', 'Dreux', 'Lucé'], density: 'mixte',
    keySectors: ['Cosmétique', 'Aéronautique', 'Agriculture'],
    economy: { tag: 'Eure-et-Loir', comment: 'Cosmetic Valley + plaine de Beauce.' },
    prospectingTip: 'Cosmétique et agroalimentaire céréalier.',
    flagshipCompanies: ['Guerlain (Chartres)', 'NovAccess (Chartres)', 'Paco Rabanne (Chartres)', 'Axéréal (coopérative)'],
    insee2024: { enterprises: '32 000', enterprisesGrowth: '+1.9 %', gdpPerCapita: '26 200 €', unemploymentRate: '7.5 %', sourceNote: 'INSEE estimation 2024' },
  },
  '18': {
    population: '300 k', topCities: ['Bourges', 'Vierzon', 'Saint-Doulchard'], density: 'rural-urbain',
    keySectors: ['Défense (MBDA, Nexter)', 'Agriculture'],
    economy: { tag: 'Cher défense', comment: 'Hub industrie défense terrestre + porcelaine.' },
    prospectingTip: 'Industrie défense.',
    flagshipCompanies: ['MBDA (Bourges)', 'Nexter Systems (KNDS) Bourges', 'Michelin (Bourges)', 'Aubade-Manufacture'],
    insee2024: { enterprises: '22 000', enterprisesGrowth: '+1.5 %', gdpPerCapita: '24 700 €', unemploymentRate: '7.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '36': {
    population: '218 k', topCities: ['Châteauroux', 'Issoudun', 'Le Blanc'], density: 'rural',
    keySectors: ['Tabac', 'Élevage', 'Logistique'],
    economy: { tag: 'Indre rurale', comment: 'Économie agricole + plateformes logistiques A20.' },
    prospectingTip: 'Logistique routière.',
    flagshipCompanies: ['Balsan (Châteauroux)', 'Mecachrome (Issoudun)', 'Sun Valley (Buzançais)', 'Bois Profilés Châteauroux'],
    insee2024: { enterprises: '17 000', enterprisesGrowth: '+1.3 %', gdpPerCapita: '23 700 €', unemploymentRate: '7.3 %', sourceNote: 'INSEE estimation 2024' },
  },
  '41': {
    population: '331 k', topCities: ['Blois', 'Vendôme', 'Romorantin'], density: 'rural-urbain',
    keySectors: ['Tourisme châteaux', 'Cosmétique', 'Édition'],
    economy: { tag: 'Loir-et-Cher', comment: 'Châteaux Loire (Chambord) + cluster cosmétique.' },
    prospectingTip: 'Tourisme premium et cosmétique.',
    flagshipCompanies: ['Procter & Gamble (Blois)', 'BioMérieux (Combronde-Vendôme)', 'Daher (Vendôme)', 'JBL France'],
    insee2024: { enterprises: '27 000', enterprisesGrowth: '+1.8 %', gdpPerCapita: '25 300 €', unemploymentRate: '7.0 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Bourgogne-Franche-Comté ────────────────────────
  '21': {
    population: '535 k', topCities: ['Dijon', 'Beaune', 'Chenôve'], density: 'urbain',
    keySectors: ['Vin (Bourgogne)', 'Pharma', 'Recherche'],
    economy: { tag: 'Dijon AOC', comment: 'Climats de Bourgogne UNESCO + Cité de la Gastronomie.' },
    prospectingTip: 'Œnotourisme et IAA gastronomique.',
    flagshipCompanies: ['Maille (Unilever)', 'Amora', 'Veolia Eau (Dijon)', 'Faurecia (Brazey-en-Plaine)'],
    insee2024: { enterprises: '48 000', enterprisesGrowth: '+2.1 %', gdpPerCapita: '27 200 €', unemploymentRate: '6.9 %', sourceNote: 'INSEE estimation 2024' },
  },
  '25': {
    population: '545 k', topCities: ['Besançon', 'Montbéliard', 'Audincourt'], density: 'urbain',
    keySectors: ['Horlogerie', 'Automobile (PSA)', 'Microtechniques'],
    economy: { tag: 'Doubs microtechnique', comment: 'Tradition horlogère + PSA Sochaux + frontière Suisse.' },
    prospectingTip: 'Microtechnique et automobile.',
    flagshipCompanies: ['Stellantis Sochaux (ex-PSA)', 'Alstom (Belfort-Montbéliard)', 'Faurecia (HQ historique)', 'Lip Horlogerie'],
    insee2024: { enterprises: '46 000', enterprisesGrowth: '+2.0 %', gdpPerCapita: '26 700 €', unemploymentRate: '7.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '39': {
    population: '258 k', topCities: ['Lons-le-Saunier', 'Dole', 'Champagnole'], density: 'rural-urbain',
    keySectors: ['Fromage (Comté)', 'Bois', 'Plasturgie'],
    economy: { tag: 'Jura comté', comment: 'AOP Comté = 1ère AOP fromagère française.' },
    prospectingTip: 'IAA fromagère et bois.',
    flagshipCompanies: ['Bel (Lons-le-Saunier — La Vache qui Rit)', 'Société Fromagère du Jura', 'Solvay (Tavaux)', 'Smoby Toys'],
    insee2024: { enterprises: '21 000', enterprisesGrowth: '+1.6 %', gdpPerCapita: '24 600 €', unemploymentRate: '5.9 %', sourceNote: 'INSEE estimation 2024' },
  },
  '58': {
    population: '202 k', topCities: ['Nevers', 'Cosne', 'Decize'], density: 'rural',
    keySectors: ['Élevage', 'Magny-Cours', 'Bois'],
    economy: { tag: 'Nièvre', comment: 'Circuit Magny-Cours + élevage charolais.' },
    prospectingTip: 'Filière équine et IAA bovine.',
    flagshipCompanies: ['Magny-Cours Technopole', 'Aperam (Imphy — aciers spéciaux)', 'Sappa (Cosne)', 'Charolais Terroir'],
    insee2024: { enterprises: '15 500', enterprisesGrowth: '+1.4 %', gdpPerCapita: '24 100 €', unemploymentRate: '7.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '70': {
    population: '233 k', topCities: ['Vesoul', 'Lure', 'Héricourt'], density: 'rural',
    keySectors: ['Automobile (PSA)', 'Bois', 'Métallurgie'],
    economy: { tag: 'Haute-Saône industrielle', comment: 'PSA Vesoul + tradition métallurgique.' },
    prospectingTip: 'Automobile et sous-traitance.',
    flagshipCompanies: ['Stellantis Vesoul (centre logistique pièces)', 'Faurecia (Marnay)', 'Parisot (Saint-Loup)', 'Lhomme (mécanique)'],
    insee2024: { enterprises: '17 000', enterprisesGrowth: '+1.5 %', gdpPerCapita: '24 100 €', unemploymentRate: '8.0 %', sourceNote: 'INSEE estimation 2024' },
  },
  '71': {
    population: '550 k', topCities: ['Chalon', 'Mâcon', 'Le Creusot'], density: 'mixte',
    keySectors: ['Vin (Mâcon)', 'Métallurgie (Le Creusot)', 'Pharmacie'],
    economy: { tag: 'Saône-et-Loire industrielle', comment: 'Le Creusot historique sidérurgique + vignobles Mâconnais.' },
    prospectingTip: 'Industrie lourde et viticulture.',
    flagshipCompanies: ['Framatome (Le Creusot — forge nucléaire)', 'Industeel (ArcelorMittal)', 'Amcor (Chalon)', 'Coca-Cola (Chalon)'],
    insee2024: { enterprises: '45 000', enterprisesGrowth: '+1.8 %', gdpPerCapita: '25 100 €', unemploymentRate: '7.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '89': {
    population: '337 k', topCities: ['Auxerre', 'Sens', 'Joigny'], density: 'rural-urbain',
    keySectors: ['Vin (Chablis)', 'Agriculture', 'Tourisme'],
    economy: { tag: 'Yonne', comment: 'Chablis + grand bassin céréalier.' },
    prospectingTip: 'Œnotourisme et agroalimentaire.',
    flagshipCompanies: ['Yapp (jus de fruits)', 'Maison Brocard (Chablis)', 'Saint-Gobain (Sens)', 'Tonnellerie François Frères'],
    insee2024: { enterprises: '25 000', enterprisesGrowth: '+1.7 %', gdpPerCapita: '24 600 €', unemploymentRate: '8.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '90': {
    population: '141 k', topCities: ['Belfort', 'Delle', 'Beaucourt'], density: 'urbain',
    keySectors: ['Énergie (Alstom)', 'Transport ferroviaire'],
    economy: { tag: 'Territoire de Belfort énergie', comment: 'Alstom + GE = hub énergétique français.' },
    prospectingTip: 'Énergie et industrie ferroviaire.',
    flagshipCompanies: ['Alstom (Belfort)', 'General Electric Power (Belfort)', 'Faurecia (Étupes proche)', 'Lisi Aerospace'],
    insee2024: { enterprises: '11 000', enterprisesGrowth: '+1.8 %', gdpPerCapita: '26 400 €', unemploymentRate: '8.6 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── Corse ─────────────────────────────────────────
  '2A': {
    population: '160 k', topCities: ['Ajaccio', 'Porto-Vecchio', 'Sartène'], density: 'rural-côtier',
    keySectors: ['Tourisme', 'Hôtellerie', 'Agriculture (clémentine)'],
    economy: { tag: 'Corse-du-Sud touristique', comment: 'Économie 100 % touristique (mai-octobre) + AOP Patrimonio.' },
    prospectingTip: 'Hors saison (nov-mars), c\'est le seul moment où démarcher.',
    flagshipCompanies: ['Corsica Ferries (siège Bastia-Ajaccio)', 'Air Corsica', 'Brasserie Pietra', 'Maison Mattei'],
    insee2024: { enterprises: '18 000', enterprisesGrowth: '+2.4 %', gdpPerCapita: '26 100 €', unemploymentRate: '7.2 %', sourceNote: 'INSEE estimation 2024' },
  },
  '2B': {
    population: '186 k', topCities: ['Bastia', 'Calvi', 'Corte'], density: 'mixte',
    keySectors: ['Tourisme', 'Ports (Bastia)', 'Vin'],
    economy: { tag: 'Haute-Corse', comment: 'Bastia = 1er port commercial de Corse + tourisme.' },
    prospectingTip: 'Saisonnalité forte : démarcher en hiver.',
    flagshipCompanies: ['Corsica Ferries (Bastia)', 'Corse Composites Aéronautiques', 'Domaine Antoine Arena (Patrimonio)', 'Université de Corse Pasquale Paoli'],
    insee2024: { enterprises: '20 000', enterprisesGrowth: '+2.3 %', gdpPerCapita: '25 800 €', unemploymentRate: '6.8 %', sourceNote: 'INSEE estimation 2024' },
  },

  // ───── DROM ──────────────────────────────────────────
  '971': {
    population: '380 k', topCities: ['Pointe-à-Pitre', 'Les Abymes', 'Baie-Mahault'], density: 'urbain littoral',
    keySectors: ['Tourisme', 'Sucre/rhum', 'BTP'],
    economy: { tag: 'Guadeloupe', comment: 'Tourisme + filière canne-sucre-rhum + BTP en reconstruction.' },
    prospectingTip: 'Tourisme et BTP. Marché restreint, ultra-ciblage.',
    flagshipCompanies: ['Damoiseau (rhum)', 'Bonbonnerie de Saint-François', 'CMA CGM Antilles', 'Gardel (sucrerie)'],
    insee2024: { enterprises: '50 000', enterprisesGrowth: '+2.6 %', gdpPerCapita: '24 100 €', unemploymentRate: '17.4 %', sourceNote: 'INSEE estimation 2024' },
  },
  '972': {
    population: '370 k', topCities: ['Fort-de-France', 'Le Lamentin', 'Schœlcher'], density: 'urbain littoral',
    keySectors: ['Tourisme', 'Rhum AOC', 'Agroalimentaire'],
    economy: { tag: 'Martinique', comment: 'AOC Rhum agricole + tourisme + filière banane.' },
    prospectingTip: 'IAA premium et tourisme. Saisonnalité décalée (haute saison décembre-avril).',
    flagshipCompanies: ['Clément (rhum AOC)', 'La Mauny (rhum)', 'Banamart (banane)', 'Air Caraïbes'],
    insee2024: { enterprises: '46 000', enterprisesGrowth: '+2.3 %', gdpPerCapita: '25 600 €', unemploymentRate: '12.8 %', sourceNote: 'INSEE estimation 2024' },
  },
  '973': {
    population: '290 k', topCities: ['Cayenne', 'Saint-Laurent', 'Kourou'], density: 'côtier + amazonien',
    keySectors: ['Spatial (Kourou)', 'Mines (or)', 'Forêt'],
    economy: { tag: 'Guyane spatiale', comment: 'Centre Spatial Guyanais + plus grand département français.' },
    prospectingTip: 'Aérospatial et BTP.',
    flagshipCompanies: ['Centre Spatial Guyanais (Arianespace, CNES)', 'Air Liquide Spatial Guyane', 'Endel-Engie (Kourou)', 'Cayenne Logistique'],
    insee2024: { enterprises: '20 000', enterprisesGrowth: '+3.4 %', gdpPerCapita: '17 200 €', unemploymentRate: '14.6 %', sourceNote: 'INSEE estimation 2024' },
  },
  '974': {
    population: '870 k', topCities: ['Saint-Denis', 'Saint-Pierre', 'Le Tampon'], density: 'urbain littoral',
    keySectors: ['Tourisme', 'Canne-sucre', 'Numérique'],
    economy: { tag: 'La Réunion', comment: 'Tourisme + plus grand bassin économique DROM + tech naissante.' },
    prospectingTip: 'Tech et tourisme. Marché le plus dynamique des DROM.',
    flagshipCompanies: ['Bourbon Tourisme', 'CMA CGM Réunion', 'Cilam (cosmétique-laitier)', 'Tereos Océan Indien (sucre)', 'Air Austral'],
    insee2024: { enterprises: '90 000', enterprisesGrowth: '+3.1 %', gdpPerCapita: '23 800 €', unemploymentRate: '17.1 %', sourceNote: 'INSEE estimation 2024' },
  },
  '976': {
    population: '300 k', topCities: ['Mamoudzou', 'Koungou', 'Dzaoudzi'], density: 'urbain en croissance',
    keySectors: ['BTP', 'Pêche', 'Services publics'],
    economy: { tag: 'Mayotte', comment: 'Plus jeune département français + forte croissance démographique.' },
    prospectingTip: 'BTP et services publics. Marché en construction.',
    flagshipCompanies: ['Colas Mayotte', 'EDM (Électricité de Mayotte)', 'Total Mayotte', 'Mayotte Channel Gateway (port)'],
    insee2024: { enterprises: '12 000', enterprisesGrowth: '+4.2 %', gdpPerCapita: '10 100 €', unemploymentRate: '30.0 %', sourceNote: 'INSEE estimation 2024 (fourchette)' },
  },
};

// Enrichissements complémentaires : notes éco récentes (legacy).
// `notableCompanies` est conservé en alias de `flagshipCompanies` pour
// rétro-compatibilité avec les blocs SEO existants (DeptContextBlock,
// DeptOverviewBlock) qui lisent `notableCompanies` historiquement.
const DEPT_ENRICHMENTS = {
  '75': { economicNote: 'Paris concentre 13 sièges du CAC 40 + le plus gros écosystème startup d\'Europe continentale.' },
  '92': { economicNote: 'La Défense = 3,5 M de m² de bureaux + 500 000 m² de bureaux à Boulogne, Issy et Levallois.' },
  '78': { economicNote: 'Versailles + Saint-Quentin-en-Yvelines = pôle automobile (Renault, PSA) + tech.' },
  '93': { economicNote: 'Saint-Denis Pleyel = nouveau hub tertiaire post-JO 2024, prix immobiliers en hausse.' },
  '94': { economicNote: 'Rungis MIN brasse 24 Md€/an de produits frais : 200 000 visiteurs par jour.' },
  '95': { economicNote: 'Roissy-CDG = 2e aéroport européen, 87 000 emplois directs.' },
  '77': { economicNote: 'Disneyland = 1er employeur privé d\'Île-de-France hors Paris (17 000 emplois).' },
  '91': { economicNote: 'Paris-Saclay = plus grand cluster scientifique européen, 13 % de la R&D française.' },
  '69': { economicNote: 'Lyon Part-Dieu = 2e quartier d\'affaires français + Vaise (numérique) + Gerland (biotechs).' },
  '38': { economicNote: 'Grenoble = 1er pôle français nanotech + Schneider Electric HQ.' },
  '63': { economicNote: 'Michelin = 12 000 emplois directs + écosystème pneu mondial.' },
  '74': { economicNote: 'Haute-Savoie = 100 000 frontaliers en Suisse + cluster sport outdoor.' },
  '73': { economicNote: 'Capitale française du ski (Courchevel, Méribel, Val Thorens).' },
  '13': { economicNote: 'Marseille-Provence = 1er port français + Aix = capitale tertiaire régionale.' },
  '06': { economicNote: 'Sophia Antipolis = plus grande technopole d\'Europe, 36 000 emplois tech.' },
  '83': { economicNote: 'Toulon = 1er port militaire français, 22 000 marins.' },
  '84': { economicNote: 'Vaucluse = 5e vignoble français + Festival d\'Avignon (1,5 M de visiteurs).' },
  '33': { economicNote: 'Bordeaux = 4e métropole pour les sièges sociaux régionaux + cluster aérospatial.' },
  '64': { economicNote: 'Pau = capitale énergie française + Bayonne-Anglet-Biarritz = pôle tertiaire basque.' },
  '17': { economicNote: 'La Rochelle = 1er port français pêche frais + base sous-marine historique.' },
  '79': { economicNote: 'Niort = capitale française du mutualisme : 15 000 emplois directs.' },
  '16': { economicNote: 'Cognac = 70 % des exports de spiritueux français (2,9 Md€).' },
  '31': { economicNote: 'Toulouse = capitale européenne aéronautique + Toulouse Space City.' },
  '34': { economicNote: 'Montpellier = pôle French Tech + cluster eHealth + 1ère croissance démographique FR.' },
  '30': { economicNote: 'Gard = patrimoine UNESCO (Pont du Gard) + filière nucléaire civile.' },
  '44': { economicNote: 'Nantes = 6e métropole française + French Tech Atlantique + chantiers navals leader mondial.' },
  '49': { economicNote: 'Angers = capitale française horticulture + Cholet = cluster textile-cuir.' },
  '85': { economicNote: 'Puy du Fou = 2,8 M de visiteurs/an, n°1 français parcs à thème en CA.' },
  '35': { economicNote: 'Rennes = pôle cybersécurité (Cyber Campus) + IUT Lannion + INRIA.' },
  '29': { economicNote: 'Finistère = 1er pôle français pêche/aquaculture + Brest = base navale nucléaire.' },
  '56': { economicNote: 'Lorient = capitale mondiale course au large + Vannes = pôle tertiaire dynamique.' },
  '22': { economicNote: 'Lannion = berceau historique télécoms français (Centre Lannion Telecom).' },
  '59': { economicNote: 'Lille = 4e métropole française + Eurométropole avec Tournai (Belgique) + n°1 distribution.' },
  '62': { economicNote: 'Calais = 1er port passagers d\'Europe continentale (10 M de passagers/an).' },
  '60': { economicNote: 'Oise = cluster cosmétique majeur (Chanel, L\'Oréal) + proximité Paris.' },
  '67': { economicNote: 'Strasbourg = 2e siège institutionnel UE après Bruxelles + cluster pharma Stratéus.' },
  '68': { economicNote: 'PSA Mulhouse = 8 000 emplois + frontière trinationale Allemagne-Suisse.' },
  '51': { economicNote: 'Champagne AOC = 5,7 Md€ de CA + 30 000 emplois directs dans la filière.' },
  '57': { economicNote: '110 000 frontaliers au Luxembourg = pouvoir d\'achat moyen le plus élevé hors IDF.' },
  '76': { economicNote: 'Le Havre = 1er port FR conteneurs + 2e pôle pétrochimique français.' },
  '14': { economicNote: 'Caen = 3e pôle français microélectronique + tourisme mémoriel D-Day (5 M de visiteurs/an).' },
  '27': { economicNote: 'Eure = cluster cosmétique Cosmetic Valley + plus grande usine pharma Sanofi (Le Trait).' },
  '37': { economicNote: 'Tours = capitale Loire + cluster pharma-cosmétique avec Pierre Fabre, Sanofi, Ipsen.' },
  '45': { economicNote: 'Orléans = pôle logistique sud Paris + cluster pharma (Servier, Boehringer).' },
  '21': { economicNote: 'Dijon = capitale gastronomique (Cité Internationale de la Gastronomie) + Côtes de Beaune.' },
  '25': { economicNote: 'PSA Sochaux = berceau historique Peugeot + cluster microtechnique Besançon.' },
  '974': { economicNote: 'La Réunion = bassin économique DROM le plus dynamique, croissance numérique et touristique forte.' },
};

/**
 * Récupère les données enrichies pour un dept (code à 2 ou 3 caractères).
 * Renvoie null si pas de data, sinon merge DEPT_DATA + DEPT_ENRICHMENTS.
 *
 * Pour rétro-compatibilité, `notableCompanies` est exposé comme alias de
 * `flagshipCompanies` (les anciens blocs SEO lisent encore `notableCompanies`).
 */
export function getDeptData(deptCode) {
  if (!deptCode) return null;
  const base = DEPT_DATA[deptCode];
  if (!base) return null;
  const enrich = DEPT_ENRICHMENTS[deptCode] || {};
  const merged = { ...base, ...enrich };
  // Alias pour rétro-compat : notableCompanies <- flagshipCompanies
  if (merged.flagshipCompanies && !merged.notableCompanies) {
    merged.notableCompanies = merged.flagshipCompanies;
  }
  return merged;
}

export { DEPT_DATA, DEPT_ENRICHMENTS };
