-- ============================================================================
-- Volia — SNAPSHOT triggers + index (schéma public) — 02/07/2026
-- Fichier de RÉFÉRENCE (perf + intégrité), pas à rejouer en prod.
-- ============================================================================

-- ─────────────────────────── TRIGGERS ───────────────────────────
CREATE TRIGGER app_settings_updated_at_trigger BEFORE UPDATE ON public.app_settings FOR EACH ROW EXECUTE FUNCTION update_app_settings_updated_at();
CREATE TRIGGER auto_blog_posts_updated_at_trigger BEFORE UPDATE ON public.auto_blog_posts FOR EACH ROW EXECUTE FUNCTION update_auto_blog_posts_updated_at();
CREATE TRIGGER auto_changelog_updated_at_trigger BEFORE UPDATE ON public.auto_changelog_proposals FOR EACH ROW EXECUTE FUNCTION update_auto_changelog_updated_at();
CREATE TRIGGER update_crm_contacts_updated_at BEFORE UPDATE ON public.crm_contacts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_crm_deals_updated_at BEFORE UPDATE ON public.crm_deals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_crm_pipelines_updated_at BEFORE UPDATE ON public.crm_pipelines FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_forms_set_updated_at BEFORE UPDATE ON public.forms FOR EACH ROW EXECUTE FUNCTION forms_set_updated_at();
CREATE TRIGGER inbound_feedback_updated_at_trigger BEFORE UPDATE ON public.inbound_feedback_emails FOR EACH ROW EXECUTE FUNCTION update_inbound_feedback_updated_at();
CREATE TRIGGER trg_project_tasks_updated BEFORE UPDATE ON public.project_tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_projects_updated BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
-- refresh des compteurs de liste à chaque mouvement de contact
CREATE TRIGGER refresh_list_counts_trigger AFTER INSERT OR DELETE OR UPDATE ON public.prospect_contacts FOR EACH ROW EXECUTE FUNCTION trigger_refresh_list_counts();
CREATE TRIGGER publisher_credentials_updated_at_trigger BEFORE UPDATE ON public.publisher_credentials FOR EACH ROW EXECUTE FUNCTION update_publisher_credentials_updated_at();
CREATE TRIGGER trg_teams_updated_at BEFORE UPDATE ON public.teams FOR EACH ROW EXECUTE FUNCTION teams_set_updated_at();
CREATE TRIGGER trg_assign_referral_code BEFORE INSERT ON public.user_profiles FOR EACH ROW EXECUTE FUNCTION assign_referral_code();
-- ⭐ garde-fou anti-élévation de privilèges + anti-auto-crédit (cf. 01_functions.sql)
-- WS1 : BEFORE INSERT OR UPDATE (couvre aussi l'INSERT forgé) + contrainte anti-solde-négatif.
CREATE TRIGGER trg_freeze_privileged_profile_columns BEFORE INSERT OR UPDATE ON public.user_profiles FOR EACH ROW EXECUTE FUNCTION freeze_privileged_profile_columns();
ALTER TABLE public.user_profiles ADD CONSTRAINT user_profiles_credit_balance_nonneg CHECK (credit_balance >= 0);
CREATE TRIGGER trg_touch_warmup_peer_pool BEFORE UPDATE ON public.warmup_peer_pool FOR EACH ROW EXECUTE FUNCTION touch_warmup_peer_pool_updated_at();

-- ─────────────────────────── INDEX ───────────────────────────
-- (inclut PK, UNIQUE et index partiels — utile pour l'audit perf F8)
CREATE INDEX aff_comm_affiliate_idx ON public.affiliate_commissions USING btree (affiliate_id);
CREATE INDEX aff_comm_customer_idx ON public.affiliate_commissions USING btree (stripe_customer_id);
CREATE INDEX aff_comm_status_idx ON public.affiliate_commissions USING btree (status);
CREATE UNIQUE INDEX affiliate_commissions_pkey ON public.affiliate_commissions USING btree (id);
CREATE UNIQUE INDEX affiliate_commissions_stripe_invoice_id_key ON public.affiliate_commissions USING btree (stripe_invoice_id);
CREATE UNIQUE INDEX affiliates_code_key ON public.affiliates USING btree (code);
CREATE INDEX affiliates_email_idx ON public.affiliates USING btree (lower(email));
CREATE UNIQUE INDEX affiliates_pkey ON public.affiliates USING btree (id);
CREATE INDEX affiliates_status_idx ON public.affiliates USING btree (status);
CREATE INDEX api_keys_active_idx ON public.api_keys USING btree (user_id) WHERE (revoked_at IS NULL);
CREATE INDEX api_keys_key_hash_idx ON public.api_keys USING btree (key_hash);
CREATE UNIQUE INDEX api_keys_key_hash_key ON public.api_keys USING btree (key_hash);
CREATE UNIQUE INDEX api_keys_pkey ON public.api_keys USING btree (id);
CREATE INDEX api_keys_user_idx ON public.api_keys USING btree (user_id);
CREATE UNIQUE INDEX api_usage_log_pkey ON public.api_usage_log USING btree (id);
CREATE INDEX idx_api_usage_month ON public.api_usage_log USING btree (month, service);
CREATE INDEX idx_api_usage_service ON public.api_usage_log USING btree (service);
CREATE UNIQUE INDEX api_usage_monthly_pkey ON public.api_usage_monthly USING btree (id);
CREATE UNIQUE INDEX api_usage_monthly_service_month_key ON public.api_usage_monthly USING btree (service, month);
CREATE UNIQUE INDEX app_settings_pkey ON public.app_settings USING btree (key);
CREATE INDEX idx_app_settings_updated_at ON public.app_settings USING btree (updated_at DESC);
CREATE UNIQUE INDEX auto_blog_posts_pkey ON public.auto_blog_posts USING btree (id);
CREATE UNIQUE INDEX auto_blog_posts_slug_key ON public.auto_blog_posts USING btree (slug);
CREATE INDEX idx_auto_blog_published ON public.auto_blog_posts USING btree (published_at DESC) WHERE (status = 'published'::text);
CREATE INDEX idx_auto_blog_slug ON public.auto_blog_posts USING btree (slug);
CREATE INDEX idx_auto_blog_status_date ON public.auto_blog_posts USING btree (status, published_at DESC);
CREATE UNIQUE INDEX auto_changelog_proposals_pkey ON public.auto_changelog_proposals USING btree (id);
CREATE INDEX idx_auto_changelog_published ON public.auto_changelog_proposals USING btree (entry_date DESC) WHERE (status = 'published'::text);
CREATE INDEX idx_auto_changelog_status_date ON public.auto_changelog_proposals USING btree (status, entry_date DESC);
CREATE UNIQUE INDEX autonomous_actions_pkey ON public.autonomous_actions USING btree (id);
CREATE INDEX idx_autonomous_actions_executed_at ON public.autonomous_actions USING btree (executed_at DESC) WHERE (status = 'executed'::text);
CREATE INDEX idx_autonomous_actions_status_created ON public.autonomous_actions USING btree (status, created_at DESC);
CREATE INDEX idx_autonomous_actions_type_created ON public.autonomous_actions USING btree (action_type, created_at DESC);
CREATE UNIQUE INDEX autonomy_metrics_daily_pkey ON public.autonomy_metrics_daily USING btree (date, action_type);
CREATE INDEX idx_autonomy_metrics_date ON public.autonomy_metrics_daily USING btree (date DESC);
CREATE UNIQUE INDEX autonomy_recommendations_pkey ON public.autonomy_recommendations USING btree (id);
CREATE INDEX idx_autonomy_recommendations_status_date ON public.autonomy_recommendations USING btree (status, created_at DESC);
CREATE UNIQUE INDEX autopilot_executions_pkey ON public.autopilot_executions USING btree (id);
CREATE UNIQUE INDEX autopilot_executions_workflow_id_prospect_id_key ON public.autopilot_executions USING btree (workflow_id, prospect_id);
CREATE INDEX idx_autopilot_executions_next_action ON public.autopilot_executions USING btree (current_step, email_1_sent_at, email_2_sent_at) WHERE (current_step = ANY (ARRAY['email_1_sent'::text, 'email_2_sent'::text, 'form_pending'::text]));
CREATE INDEX idx_autopilot_executions_workflow_step ON public.autopilot_executions USING btree (workflow_id, current_step);
CREATE UNIQUE INDEX autopilot_runs_pkey ON public.autopilot_runs USING btree (id);
CREATE INDEX idx_autopilot_runs_workflow_date ON public.autopilot_runs USING btree (workflow_id, started_at DESC);
CREATE UNIQUE INDEX autopilot_workflows_pkey ON public.autopilot_workflows USING btree (id);
CREATE INDEX idx_autopilot_workflows_next_run ON public.autopilot_workflows USING btree (next_run_at) WHERE (status = 'active'::text);
CREATE INDEX idx_autopilot_workflows_user_status ON public.autopilot_workflows USING btree (user_id, status);
CREATE UNIQUE INDEX checkout_recovery_attempts_pkey ON public.checkout_recovery_attempts USING btree (id);
CREATE UNIQUE INDEX checkout_recovery_attempts_stripe_session_id_key ON public.checkout_recovery_attempts USING btree (stripe_session_id);
CREATE INDEX idx_checkout_recovery_session_expired ON public.checkout_recovery_attempts USING btree (session_expired_at DESC);
CREATE UNIQUE INDEX credit_transactions_pkey ON public.credit_transactions USING btree (id);
CREATE UNIQUE INDEX credit_transactions_stripe_session_id_key ON public.credit_transactions USING btree (stripe_session_id);
CREATE INDEX credit_transactions_user_idx ON public.credit_transactions USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX crm_activities_pkey ON public.crm_activities USING btree (id);
CREATE INDEX idx_crm_activities_contact ON public.crm_activities USING btree (contact_id) WHERE (contact_id IS NOT NULL);
CREATE INDEX idx_crm_activities_deal ON public.crm_activities USING btree (deal_id) WHERE (deal_id IS NOT NULL);
CREATE INDEX idx_crm_activities_metadata_source ON public.crm_activities USING gin (metadata) WHERE (metadata ? 'source'::text);
CREATE INDEX idx_crm_activities_user_due ON public.crm_activities USING btree (user_id, due_at) WHERE ((due_at IS NOT NULL) AND (completed_at IS NULL));
CREATE UNIQUE INDEX crm_contacts_pkey ON public.crm_contacts USING btree (id);
CREATE INDEX idx_crm_contacts_email ON public.crm_contacts USING btree (user_id, email) WHERE (email IS NOT NULL);
CREATE INDEX idx_crm_contacts_user ON public.crm_contacts USING btree (user_id);
CREATE UNIQUE INDEX idx_crm_contacts_user_email_unique ON public.crm_contacts USING btree (user_id, lower(email)) WHERE (email IS NOT NULL);
CREATE UNIQUE INDEX crm_custom_fields_pkey ON public.crm_custom_fields USING btree (id);
CREATE UNIQUE INDEX crm_custom_fields_user_id_entity_field_key_key ON public.crm_custom_fields USING btree (user_id, entity, field_key);
CREATE INDEX idx_crm_custom_fields_user_entity ON public.crm_custom_fields USING btree (user_id, entity) WHERE (archived = false);
CREATE UNIQUE INDEX crm_deals_pkey ON public.crm_deals USING btree (id);
CREATE INDEX idx_crm_deals_contact ON public.crm_deals USING btree (contact_id);
CREATE INDEX idx_crm_deals_metadata_auto_created ON public.crm_deals USING gin (metadata) WHERE (metadata ? 'auto_created'::text);
CREATE INDEX idx_crm_deals_pipeline_stage ON public.crm_deals USING btree (pipeline_id, stage_id, "position");
CREATE INDEX idx_crm_deals_stage ON public.crm_deals USING btree (stage_id);
CREATE INDEX idx_crm_deals_user ON public.crm_deals USING btree (user_id);
CREATE UNIQUE INDEX crm_pipelines_pkey ON public.crm_pipelines USING btree (id);
CREATE INDEX idx_crm_pipelines_user ON public.crm_pipelines USING btree (user_id);
CREATE UNIQUE INDEX crm_stages_pkey ON public.crm_stages USING btree (id);
CREATE INDEX idx_crm_stages_pipeline ON public.crm_stages USING btree (pipeline_id);
CREATE UNIQUE INDEX decision_maker_contacts_domain_role_key ON public.decision_maker_contacts USING btree (domain, role);
CREATE UNIQUE INDEX decision_maker_contacts_pkey ON public.decision_maker_contacts USING btree (id);
CREATE INDEX idx_dmc_domain_role ON public.decision_maker_contacts USING btree (domain, role);
CREATE UNIQUE INDEX demo_bot_conversations_pkey ON public.demo_bot_conversations USING btree (id);
CREATE INDEX idx_demo_bot_demo_request ON public.demo_bot_conversations USING btree (started_at DESC) WHERE (has_demo_request = true);
CREATE INDEX idx_demo_bot_session ON public.demo_bot_conversations USING btree (session_id);
CREATE INDEX idx_demo_bot_started_at ON public.demo_bot_conversations USING btree (started_at DESC);
CREATE UNIQUE INDEX dogfood_outreach_history_pkey ON public.dogfood_outreach_history USING btree (id);
CREATE UNIQUE INDEX dogfood_outreach_history_place_id_key ON public.dogfood_outreach_history USING btree (place_id);
CREATE INDEX idx_dogfood_history_added_at ON public.dogfood_outreach_history USING btree (added_at DESC);
CREATE INDEX email_campaigns_owner_idx ON public.email_campaigns USING btree (owner_id, created_at DESC);
CREATE UNIQUE INDEX email_campaigns_pkey ON public.email_campaigns USING btree (id);
CREATE INDEX email_campaigns_status_idx ON public.email_campaigns USING btree (status) WHERE (status = ANY (ARRAY['scheduled'::text, 'sending'::text]));
CREATE INDEX idx_email_campaigns_sender_id ON public.email_campaigns USING btree (email_sender_id);
CREATE UNIQUE INDEX email_senders_pkey ON public.email_senders USING btree (id);
CREATE UNIQUE INDEX email_senders_user_id_domain_key ON public.email_senders USING btree (user_id, domain);
CREATE INDEX idx_email_senders_user_id ON public.email_senders USING btree (user_id);
CREATE UNIQUE INDEX email_sends_campaign_contact_unique ON public.email_sends USING btree (campaign_id, contact_id) WHERE ((campaign_id IS NOT NULL) AND (contact_id IS NOT NULL));
CREATE INDEX email_sends_campaign_idx ON public.email_sends USING btree (campaign_id, status);
CREATE INDEX email_sends_pending_idx ON public.email_sends USING btree (status, created_at) WHERE (status = 'pending'::text);
-- WS5 : claim atomique anti-double-envoi (colonne email_sends.claimed_at ajoutée par migration 20260704_ws5_email_sends_claim)
CREATE INDEX idx_email_sends_pending_claim ON public.email_sends USING btree (claimed_at) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX email_sends_pkey ON public.email_sends USING btree (id);
CREATE INDEX email_sends_provider_idx ON public.email_sends USING btree (provider_id) WHERE (provider_id IS NOT NULL);
CREATE INDEX idx_email_sends_provider_id ON public.email_sends USING btree (provider_id) WHERE (provider_id IS NOT NULL);
CREATE INDEX idx_email_sends_scheduled_for ON public.email_sends USING btree (scheduled_for) WHERE ((status = 'pending'::text) AND (scheduled_for IS NOT NULL));
CREATE INDEX idx_email_sends_sequence_enrollment ON public.email_sends USING btree (sequence_enrollment_id) WHERE (sequence_enrollment_id IS NOT NULL);
CREATE INDEX idx_email_sends_subject_variant ON public.email_sends USING btree (campaign_id, subject_variant);
CREATE UNIQUE INDEX email_sequences_pkey ON public.email_sequences USING btree (id);
CREATE INDEX idx_email_sequences_owner_id ON public.email_sequences USING btree (owner_id);
CREATE INDEX idx_email_sequences_status_active ON public.email_sequences USING btree (status) WHERE (status = 'active'::text);
CREATE INDEX enrichment_jobs_active_idx ON public.enrichment_jobs USING btree (status) WHERE (status = ANY (ARRAY['queued'::text, 'running'::text]));
CREATE UNIQUE INDEX enrichment_jobs_one_active_per_user ON public.enrichment_jobs USING btree (user_id) WHERE (status = ANY (ARRAY['queued'::text, 'running'::text, 'paused'::text]));
CREATE UNIQUE INDEX enrichment_jobs_pkey ON public.enrichment_jobs USING btree (id);
CREATE UNIQUE INDEX form_fields_pkey ON public.form_fields USING btree (id);
CREATE UNIQUE INDEX idx_form_fields_form_key_unique ON public.form_fields USING btree (form_id, field_key);
CREATE INDEX idx_form_fields_form_position ON public.form_fields USING btree (form_id, "position");
CREATE UNIQUE INDEX form_files_pkey ON public.form_files USING btree (id);
CREATE INDEX idx_form_files_response ON public.form_files USING btree (form_response_id);
CREATE INDEX form_responses_bridge_retry_idx ON public.form_responses USING btree (bridge_next_retry_at) WHERE ((bridge_status = 'failed'::text) AND (bridge_retry_count < 3));
CREATE UNIQUE INDEX form_responses_pkey ON public.form_responses USING btree (id);
CREATE INDEX idx_form_responses_bridge_pending ON public.form_responses USING btree (bridge_status) WHERE (bridge_status = 'pending'::text);
CREATE INDEX idx_form_responses_form_submitted ON public.form_responses USING btree (form_id, submitted_at DESC);
CREATE INDEX idx_form_responses_user ON public.form_responses USING btree (user_id);
CREATE INDEX form_templates_category_position_idx ON public.form_templates USING btree (category, "position");
CREATE UNIQUE INDEX form_templates_pkey ON public.form_templates USING btree (id);
CREATE UNIQUE INDEX form_templates_slug_key ON public.form_templates USING btree (slug);
CREATE UNIQUE INDEX forms_pkey ON public.forms USING btree (id);
CREATE UNIQUE INDEX forms_slug_key ON public.forms USING btree (slug);
CREATE INDEX idx_forms_user_status ON public.forms USING btree (user_id, status);
CREATE UNIQUE INDEX global_contacts_domain_key ON public.global_contacts USING btree (domain);
CREATE UNIQUE INDEX global_contacts_pkey ON public.global_contacts USING btree (id);
CREATE INDEX idx_global_contacts_domain ON public.global_contacts USING btree (domain);
CREATE INDEX idx_global_contacts_place ON public.global_contacts USING btree (place_id) WHERE (place_id IS NOT NULL);
CREATE UNIQUE INDEX immo_waitlist_email_key ON public.immo_waitlist USING btree (lower(email));
CREATE UNIQUE INDEX immo_waitlist_pkey ON public.immo_waitlist USING btree (id);
CREATE INDEX idx_inbound_events_contact_id ON public.inbound_events USING btree (contact_id);
CREATE INDEX idx_inbound_events_created_at ON public.inbound_events USING btree (created_at DESC);
CREATE INDEX idx_inbound_events_deal_id ON public.inbound_events USING btree (deal_id);
CREATE INDEX idx_inbound_events_user_id ON public.inbound_events USING btree (user_id);
CREATE UNIQUE INDEX inbound_events_pkey ON public.inbound_events USING btree (id);
CREATE INDEX idx_inbound_feedback_category ON public.inbound_feedback_emails USING btree (category, received_at DESC);
CREATE INDEX idx_inbound_feedback_from ON public.inbound_feedback_emails USING btree (from_email);
CREATE INDEX idx_inbound_feedback_received ON public.inbound_feedback_emails USING btree (received_at DESC);
CREATE UNIQUE INDEX inbound_feedback_emails_pkey ON public.inbound_feedback_emails USING btree (id);
CREATE UNIQUE INDEX inbound_feedback_emails_raw_email_id_key ON public.inbound_feedback_emails USING btree (raw_email_id);
CREATE INDEX idx_lead_folders_user_id ON public.lead_folders USING btree (user_id);
CREATE UNIQUE INDEX lead_folders_pkey ON public.lead_folders USING btree (id);
CREATE INDEX idx_lead_tags_user_id ON public.lead_tags USING btree (user_id);
CREATE UNIQUE INDEX lead_tags_pkey ON public.lead_tags USING btree (id);
CREATE INDEX idx_linkedin_dm_queue_status_date ON public.linkedin_dm_queue USING btree (status, detected_at DESC);
CREATE UNIQUE INDEX linkedin_dm_queue_li_urn_key ON public.linkedin_dm_queue USING btree (li_urn);
CREATE UNIQUE INDEX linkedin_dm_queue_pkey ON public.linkedin_dm_queue USING btree (id);
CREATE INDEX idx_newsletter_subscribers_active ON public.newsletter_subscribers USING btree (email) WHERE (unsubscribed_at IS NULL);
CREATE INDEX idx_newsletter_subscribers_email ON public.newsletter_subscribers USING btree (email);
CREATE INDEX idx_newsletter_subscribers_unsubscribe_token ON public.newsletter_subscribers USING btree (unsubscribe_token);
CREATE UNIQUE INDEX newsletter_subscribers_email_key ON public.newsletter_subscribers USING btree (email);
CREATE UNIQUE INDEX newsletter_subscribers_pkey ON public.newsletter_subscribers USING btree (id);
CREATE UNIQUE INDEX newsletter_subscribers_unsubscribe_token_key ON public.newsletter_subscribers USING btree (unsubscribe_token);
CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);
CREATE INDEX notifications_user_created_idx ON public.notifications USING btree (user_id, created_at DESC) WHERE (archived_at IS NULL);
CREATE INDEX notifications_user_unread_idx ON public.notifications USING btree (user_id, read_at) WHERE ((read_at IS NULL) AND (archived_at IS NULL));
CREATE INDEX idx_opt_out_list_email ON public.opt_out_list USING btree (email);
CREATE UNIQUE INDEX opt_out_list_email_key ON public.opt_out_list USING btree (email);
CREATE UNIQUE INDEX opt_out_list_pkey ON public.opt_out_list USING btree (id);
CREATE UNIQUE INDEX product_hunt_launches_pkey ON public.product_hunt_launches USING btree (id);
CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);
CREATE INDEX idx_project_activity_project ON public.project_activity USING btree (project_id, created_at DESC);
CREATE UNIQUE INDEX project_activity_pkey ON public.project_activity USING btree (id);
CREATE INDEX idx_project_attachments_project ON public.project_attachments USING btree (project_id);
CREATE INDEX idx_project_attachments_task ON public.project_attachments USING btree (task_id) WHERE (task_id IS NOT NULL);
CREATE INDEX idx_project_attachments_uploader ON public.project_attachments USING btree (uploaded_by) WHERE (uploaded_by IS NOT NULL);
CREATE UNIQUE INDEX project_attachments_pkey ON public.project_attachments USING btree (id);
CREATE INDEX idx_project_deliverables_attachment ON public.project_deliverables USING btree (attachment_id) WHERE (attachment_id IS NOT NULL);
CREATE INDEX idx_project_deliverables_project ON public.project_deliverables USING btree (project_id);
CREATE UNIQUE INDEX project_deliverables_pkey ON public.project_deliverables USING btree (id);
CREATE INDEX idx_project_shares_project ON public.project_shares USING btree (project_id);
CREATE INDEX idx_project_shares_token ON public.project_shares USING btree (token);
CREATE UNIQUE INDEX project_shares_pkey ON public.project_shares USING btree (id);
CREATE UNIQUE INDEX project_shares_token_key ON public.project_shares USING btree (token);
CREATE INDEX idx_project_task_comments_task ON public.project_task_comments USING btree (task_id);
CREATE INDEX idx_project_task_comments_user ON public.project_task_comments USING btree (user_id);
CREATE UNIQUE INDEX project_task_comments_pkey ON public.project_task_comments USING btree (id);
CREATE INDEX idx_project_tasks_due ON public.project_tasks USING btree (due_at) WHERE (status <> 'done'::text);
CREATE INDEX idx_project_tasks_project ON public.project_tasks USING btree (project_id, status, "position");
CREATE UNIQUE INDEX project_tasks_pkey ON public.project_tasks USING btree (id);
CREATE INDEX idx_project_templates_user ON public.project_templates USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE UNIQUE INDEX project_templates_pkey ON public.project_templates USING btree (id);
CREATE INDEX idx_projects_crm_contact ON public.projects USING btree (crm_contact_id) WHERE (crm_contact_id IS NOT NULL);
CREATE INDEX idx_projects_crm_deal ON public.projects USING btree (crm_deal_id) WHERE (crm_deal_id IS NOT NULL);
CREATE INDEX idx_projects_user ON public.projects USING btree (user_id, status);
CREATE UNIQUE INDEX projects_pkey ON public.projects USING btree (id);
CREATE INDEX prospect_contacts_email_idx ON public.prospect_contacts USING btree (email) WHERE (email IS NOT NULL);
CREATE INDEX prospect_contacts_list_idx ON public.prospect_contacts USING btree (list_id);
CREATE INDEX prospect_contacts_opt_out_idx ON public.prospect_contacts USING btree (opt_out) WHERE (opt_out = true);
CREATE INDEX prospect_contacts_phone_idx ON public.prospect_contacts USING btree (phone) WHERE (phone IS NOT NULL);
CREATE UNIQUE INDEX prospect_contacts_pkey ON public.prospect_contacts USING btree (id);
CREATE UNIQUE INDEX prospect_contacts_unique_email_per_list ON public.prospect_contacts USING btree (list_id, email);
CREATE UNIQUE INDEX prospect_contacts_unique_phone_per_list ON public.prospect_contacts USING btree (list_id, phone);
CREATE INDEX prospect_lists_owner_idx ON public.prospect_lists USING btree (owner_id, created_at DESC);
CREATE UNIQUE INDEX prospect_lists_pkey ON public.prospect_lists USING btree (id);
CREATE INDEX idx_prospect_tags_prospect_id ON public.prospect_tags USING btree (prospect_id);
CREATE INDEX idx_prospect_tags_tag_id ON public.prospect_tags USING btree (tag_id);
CREATE UNIQUE INDEX prospect_tags_pkey ON public.prospect_tags USING btree (prospect_id, tag_id);
CREATE INDEX idx_prospects_archived ON public.prospects USING btree (user_id, archived_at) WHERE (archived_at IS NOT NULL);
CREATE INDEX idx_prospects_folder_id ON public.prospects USING btree (folder_id);
CREATE INDEX idx_prospects_place_id ON public.prospects USING btree (place_id);
CREATE INDEX idx_prospects_user_created ON public.prospects USING btree (user_id, created_at DESC);
CREATE INDEX idx_prospects_user_id ON public.prospects USING btree (user_id);
CREATE UNIQUE INDEX prospects_pkey ON public.prospects USING btree (id);
CREATE UNIQUE INDEX prospects_user_id_place_id_key ON public.prospects USING btree (user_id, place_id);
CREATE INDEX idx_publisher_credentials_platform_enabled ON public.publisher_credentials USING btree (platform, enabled);
CREATE UNIQUE INDEX publisher_credentials_pkey ON public.publisher_credentials USING btree (id);
CREATE UNIQUE INDEX publisher_credentials_platform_unique ON public.publisher_credentials USING btree (platform);
CREATE INDEX idx_referrals_referred ON public.referrals USING btree (referred_id);
CREATE UNIQUE INDEX idx_referrals_referred_unique ON public.referrals USING btree (referred_id) WHERE (referred_id IS NOT NULL);
CREATE INDEX idx_referrals_referrer ON public.referrals USING btree (referrer_id);
CREATE INDEX idx_referrals_status ON public.referrals USING btree (status);
CREATE UNIQUE INDEX referrals_pkey ON public.referrals USING btree (id);
CREATE INDEX resource_leads_created_at_idx ON public.resource_leads USING btree (created_at DESC);
CREATE INDEX resource_leads_email_idx ON public.resource_leads USING btree (email);
CREATE UNIQUE INDEX resource_leads_pkey ON public.resource_leads USING btree (id);
CREATE INDEX resource_leads_resource_slug_idx ON public.resource_leads USING btree (resource_slug);
CREATE UNIQUE INDEX resource_leads_unique_email_resource ON public.resource_leads USING btree (email, resource_slug);
CREATE INDEX idx_search_sessions_user_id ON public.search_sessions USING btree (user_id);
CREATE UNIQUE INDEX search_sessions_pkey ON public.search_sessions USING btree (id);
CREATE INDEX idx_sequence_enrollments_contact_id ON public.sequence_enrollments USING btree (contact_id);
CREATE INDEX idx_sequence_enrollments_next_send ON public.sequence_enrollments USING btree (next_send_at) WHERE (status = 'active'::text);
CREATE INDEX idx_sequence_enrollments_sequence_id ON public.sequence_enrollments USING btree (sequence_id);
CREATE UNIQUE INDEX sequence_enrollments_pkey ON public.sequence_enrollments USING btree (id);
CREATE UNIQUE INDEX sequence_enrollments_sequence_id_contact_id_key ON public.sequence_enrollments USING btree (sequence_id, contact_id);
CREATE INDEX idx_sequence_steps_sequence_id ON public.sequence_steps USING btree (sequence_id);
CREATE UNIQUE INDEX sequence_steps_pkey ON public.sequence_steps USING btree (id);
CREATE UNIQUE INDEX sequence_steps_sequence_id_step_order_key ON public.sequence_steps USING btree (sequence_id, step_order);
CREATE INDEX idx_sms_campaigns_sender_id ON public.sms_campaigns USING btree (sms_sender_id);
CREATE INDEX sms_campaigns_owner_idx ON public.sms_campaigns USING btree (owner_id, created_at DESC);
CREATE UNIQUE INDEX sms_campaigns_pkey ON public.sms_campaigns USING btree (id);
CREATE INDEX sms_campaigns_status_idx ON public.sms_campaigns USING btree (status) WHERE (status = ANY (ARRAY['scheduled'::text, 'sending'::text]));
CREATE INDEX idx_sms_senders_user_id ON public.sms_senders USING btree (user_id);
CREATE UNIQUE INDEX sms_senders_pkey ON public.sms_senders USING btree (id);
CREATE UNIQUE INDEX sms_senders_user_id_phone_number_key ON public.sms_senders USING btree (user_id, phone_number);
CREATE INDEX idx_sms_sends_provider_id ON public.sms_sends USING btree (provider_id) WHERE (provider_id IS NOT NULL);
CREATE INDEX sms_sends_campaign_idx ON public.sms_sends USING btree (campaign_id, status);
CREATE INDEX sms_sends_pending_idx ON public.sms_sends USING btree (status, created_at) WHERE (status = 'pending'::text);
CREATE UNIQUE INDEX sms_sends_pkey ON public.sms_sends USING btree (id);
CREATE UNIQUE INDEX stripe_webhook_events_pkey ON public.stripe_webhook_events USING btree (id);
CREATE INDEX idx_team_invitations_email ON public.team_invitations USING btree (lower(email)) WHERE (accepted_at IS NULL);
CREATE INDEX idx_team_invitations_team ON public.team_invitations USING btree (team_id);
CREATE INDEX idx_team_invitations_token ON public.team_invitations USING btree (token) WHERE (accepted_at IS NULL);
CREATE UNIQUE INDEX team_invitations_pkey ON public.team_invitations USING btree (id);
CREATE UNIQUE INDEX team_invitations_token_key ON public.team_invitations USING btree (token);
CREATE INDEX idx_team_members_team ON public.team_members USING btree (team_id);
CREATE INDEX idx_team_members_user ON public.team_members USING btree (user_id);
CREATE UNIQUE INDEX team_members_pkey ON public.team_members USING btree (id);
CREATE UNIQUE INDEX team_members_team_id_user_id_key ON public.team_members USING btree (team_id, user_id);
CREATE INDEX idx_teams_owner ON public.teams USING btree (owner_id);
CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);
CREATE INDEX idx_usage_tracking_user_month ON public.usage_tracking USING btree (user_id, month);
CREATE UNIQUE INDEX usage_tracking_pkey ON public.usage_tracking USING btree (id);
CREATE UNIQUE INDEX usage_tracking_user_id_month_key ON public.usage_tracking USING btree (user_id, month);
CREATE UNIQUE INDEX user_achievements_pkey ON public.user_achievements USING btree (id);
CREATE INDEX user_achievements_unseen_idx ON public.user_achievements USING btree (user_id, unlocked_at) WHERE (toast_shown_at IS NULL);
CREATE UNIQUE INDEX user_achievements_user_id_achievement_key_key ON public.user_achievements USING btree (user_id, achievement_key);
CREATE INDEX user_achievements_user_idx ON public.user_achievements USING btree (user_id, unlocked_at DESC);
CREATE INDEX idx_user_profiles_churned_at ON public.user_profiles USING btree (churned_at) WHERE (churned_at IS NOT NULL);
CREATE INDEX idx_user_profiles_drip_emails_sent ON public.user_profiles USING gin (drip_emails_sent);
CREATE INDEX idx_user_profiles_lead_score ON public.user_profiles USING btree (lead_score DESC) WHERE (lead_score > 0);
CREATE INDEX idx_user_profiles_onboarding_completed ON public.user_profiles USING btree (onboarding_completed_at) WHERE (onboarding_completed_at IS NULL);
CREATE INDEX idx_user_profiles_referral_code ON public.user_profiles USING btree (referral_code);
CREATE INDEX idx_user_profiles_referred_by_code ON public.user_profiles USING btree (referred_by_code);
CREATE INDEX idx_user_profiles_team ON public.user_profiles USING btree (team_id);
CREATE INDEX idx_user_profiles_trial_ends_at ON public.user_profiles USING btree (trial_ends_at) WHERE ((trial_ends_at IS NOT NULL) AND (trial_converted_at IS NULL));
CREATE INDEX user_profiles_affiliate_idx ON public.user_profiles USING btree (affiliate_id);
CREATE UNIQUE INDEX user_profiles_pkey ON public.user_profiles USING btree (id);
CREATE UNIQUE INDEX user_profiles_referral_code_key ON public.user_profiles USING btree (referral_code);
CREATE INDEX idx_volia_one_runs_owner_created ON public.volia_one_runs USING btree (owner_id, created_at DESC);
CREATE UNIQUE INDEX volia_one_runs_pkey ON public.volia_one_runs USING btree (id);
CREATE INDEX idx_warmup_exchanges_from ON public.warmup_exchanges USING btree (from_peer_id);
CREATE INDEX idx_warmup_exchanges_resend_message ON public.warmup_exchanges USING btree (resend_message_id) WHERE (resend_message_id IS NOT NULL);
CREATE INDEX idx_warmup_exchanges_sent_at ON public.warmup_exchanges USING btree (sent_at DESC);
CREATE INDEX idx_warmup_exchanges_to ON public.warmup_exchanges USING btree (to_peer_id);
CREATE UNIQUE INDEX warmup_exchanges_pkey ON public.warmup_exchanges USING btree (id);
CREATE INDEX idx_warmup_peer_pool_active ON public.warmup_peer_pool USING btree (active) WHERE (active = true);
CREATE INDEX idx_warmup_peer_pool_sender ON public.warmup_peer_pool USING btree (sender_id);
CREATE UNIQUE INDEX warmup_peer_pool_pkey ON public.warmup_peer_pool USING btree (id);
CREATE UNIQUE INDEX warmup_peer_pool_sender_id_key ON public.warmup_peer_pool USING btree (sender_id);
CREATE INDEX idx_warmup_sessions_status ON public.warmup_sessions USING btree (status) WHERE (status = 'active'::text);
CREATE INDEX idx_warmup_sessions_user_id ON public.warmup_sessions USING btree (user_id);
CREATE UNIQUE INDEX warmup_sessions_pkey ON public.warmup_sessions USING btree (id);
CREATE UNIQUE INDEX warmup_sessions_sender_id_key ON public.warmup_sessions USING btree (sender_id);
CREATE INDEX idx_webhook_deliveries_failed ON public.webhook_deliveries USING btree (success, attempted_at DESC) WHERE (success = false);
CREATE INDEX idx_webhook_deliveries_subscription ON public.webhook_deliveries USING btree (subscription_id, attempted_at DESC);
CREATE INDEX idx_webhook_deliveries_user ON public.webhook_deliveries USING btree (user_id, attempted_at DESC);
CREATE UNIQUE INDEX webhook_deliveries_pkey ON public.webhook_deliveries USING btree (id);
CREATE INDEX idx_webhook_events_created_at ON public.webhook_events USING btree (created_at DESC);
CREATE INDEX idx_webhook_events_provider_event ON public.webhook_events USING btree (provider, provider_event_id);
CREATE UNIQUE INDEX webhook_events_pkey ON public.webhook_events USING btree (id);
CREATE UNIQUE INDEX webhook_events_provider_event_uniq ON public.webhook_events USING btree (provider, provider_event_id) WHERE (provider_event_id IS NOT NULL);
CREATE INDEX idx_webhook_subs_active_events ON public.webhook_subscriptions USING btree (active) WHERE (active = true);
CREATE INDEX idx_webhook_subs_user ON public.webhook_subscriptions USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX webhook_subscriptions_pkey ON public.webhook_subscriptions USING btree (id);
